### ISSUE TITLE
ERROR: Memory: bad allocation size

### ISSUE THREAD

**Issue by Machine-Maker** [gildor2/UEViewer#137]
So, in unpacking a game's pak files, I get this issue for only a few files. All the other files work just fine. I found some answers saying the game might not be supported but since a large majority of the other assets open/export just fine, I thought this might be something else. I also saw a response saying the ue version might be off. While I'm not sure exactly of the games engine version, I know its later than 4.20 since most stuff doesn't work with versions before it. I tried opening it with 4.20, 21, 22, and 23 and got the same error (below) both times. Any suggestions to try?

`Loading package: /Game/Mist/UI/Widgets/RealmMap/Assets/M_Background.uasset Ver: 517/0 Engine: 0 [Unversioned] Names: 94 Exports: 30 Imports: 35 Game: 1000150
Full package loaded in 0.0 sec, 4 allocs, 0.00 MBytes serialized in 0 calls.
Loading Material3 M_Background from package /Game/Mist/UI/Widgets/RealmMap/Assets/M_Background.uasset
WARNING: ByteProperty "UMaterial3::MaterialDomain" was not found
WARNING: ArrayProperty "UMaterial3::MaterialFunctionInfos" was not found
WARNING: BoolProperty "UMaterial3::bCanMaskedBeAssumedOpaque" was not found
WARNING: StructProperty "UMaterial3::StateId" was not found
WARNING: ArrayProperty "UMaterial3::CachedQualityLevelsUsed" was not found
WARNING: Import(Material'Default__Material'): package /Script/Engine was not found
WARNING: Import(MaterialExpressionMaterialFunctionCall'Default__MaterialExpressionMaterialFunctionCall'): package /Script/Engine was not found
WARNING: Import(MaterialExpressionScalarParameter'Default__MaterialExpressionScalarParameter'): package /Script/Engine was not found
WARNING: Import(MaterialExpressionTextureSample'Default__MaterialExpressionTextureSample'): package /Script/Engine was not found
WARNING: Import(MaterialExpressionVectorParameter'Default__MaterialExpressionVectorParameter'): package /Script/Engine was not found
Loading package: /Engine/Functions/Engine_MaterialFunctions01/Density/ExponentialDensity.uasset Ver: 517/0 Engine: 0 [Unversioned] Names: 19 Exports: 1 Imports: 3 Game: 1000150
WARNING: Unknown class "MaterialFunction" for object "ExponentialDensity"
Loading package: /Engine/Functions/Engine_MaterialFunctions01/Gradient/RadialGradient.uasset Ver: 517/0 Engine: 0 [Unversioned] Names: 17 Exports: 1 Imports: 3 Game: 1000150
WARNING: Unknown class "MaterialFunction" for object "RadialGradient"
Loading package: /Engine/Functions/Engine_MaterialFunctions01/Gradient/RadialGradientExponential.uasset Ver: 517/0 Engine: 0 [Unversioned] Names: 24 Exports: 3 Imports: 7 Game: 1000150
WARNING: Unknown class "MaterialFunction" for object "RadialGradientExponential"
Loading package: /Engine/Functions/Engine_MaterialFunctions01/Vectors/RotateVector.uasset Ver: 517/0 Engine: 0 [Unversioned] Names: 19 Exports: 1 Imports: 3 Game: 1000150
WARNING: Unknown class "MaterialFunction" for object "RotateVector"
Loading package: /Engine/Functions/Engine_MaterialFunctions02/Math/TimeWithSpeedVariable.uasset Ver: 517/0 Engine: 0 [Unversioned] Names: 19 Exports: 1 Imports: 3 Game: 1000150
WARNING: Unknown class "MaterialFunction" for object "TimeWithSpeedVariable"
Loading package: /Engine/Functions/Engine_MaterialFunctions02/Texturing/CustomRotator.uasset Ver: 517/0 Engine: 0 [Unversioned] Names: 19 Exports: 1 Imports: 3 Game: 1000150
WARNING: Unknown class "MaterialFunction" for object "CustomRotator"
Loading package: /Game/Mist/Effects/UltraDynamicSky/Materials/MF_CloudLayer.uasset Ver: 517/0 Engine: 0 [Unversioned] Names: 73 Exports: 36 Imports: 25 Game: 1000150
WARNING: Unknown class "MaterialFunction" for object "MF_CloudLayer"
Loading package: /Game/Mist/Effects/UltraDynamicSky/Materials/MF_FilterClouds.uasset Ver: 517/0 Engine: 0 [Unversioned] Names: 15 Exports: 1 Imports: 3 Game: 1000150
WARNING: Unknown class "MaterialFunction" for object "MF_FilterClouds"
Loading package: /Game/Mist/Effects/HeatPP/Grass_Noise.uasset Ver: 517/0 Engine: 0 [Unversioned] Names: 21 Exports: 1 Imports: 3 Game: 1000150
Loading package: /Game/Mist/Props/Nature/TataouineRocks/Particles/Textures/T_Dust_01.uasset Ver: 517/0 Engine: 0 [Unversioned] Names: 18 Exports: 1 Imports: 3 Game: 1000150
Loading package: /Game/Mist/Props/Nature/TataouineRocks/Particles/Textures/T_Dust_02.uasset Ver: 517/0 Engine: 0 [Unversioned] Names: 15 Exports: 1 Imports: 3 Game: 1000150
Loading package: /Game/Mist/UI/Widgets/RealmMap/Assets/T_WorldMapBackground_D.uasset Ver: 517/0 Engine: 0 [Unversioned] Names: 17 Exports: 1 Imports: 3 Game: 1000150
Loading Texture2D Grass_Noise from package /Game/Mist/Effects/HeatPP/Grass_Noise.uasset
Loading data for format PF_G8 ...
Loading Texture2D T_Dust_01 from package /Game/Mist/Props/Nature/TataouineRocks/Particles/Textures/T_Dust_01.uasset
Loading data for format PF_DXT1 ...
Loading Texture2D T_Dust_02 from package /Game/Mist/Props/Nature/TataouineRocks/Particles/Textures/T_Dust_02.uasset
Loading data for format PF_DXT1 ...
Loading Texture2D T_WorldMapBackground_D from package /Game/Mist/UI/Widgets/RealmMap/Assets/T_WorldMapBackground_D.uasset
Loading data for format PF_B8G8R8A8 ...
******** Loading object Texture2D'T_WorldMapBackground_D.T_WorldMapBackground_D' ********
*** ERROR: Memory: bad allocation size 472366756 bytes
appMalloc:size=472366756 (total=17 Mbytes) <- FByteBulkData::SerializeDataChunk <- FByteBulkData::Serialize <- FTexture2DMipMap::Serialize4 <- TArray::Serialize: 0/1 <- FTexturePlatformData<< <- UTexture2D::Ser
ialize4 <- UTexture2D::Serialize <- LoadObject:Texture2D'T_WorldMapBackground_D.T_WorldMapBackground_D', pos=40C, ver=517/0 (unversioned), game=ue4.21 <- UObject::EndLoad <- Main:umodel_build=1021`

**Comment by gildor2** [comment]
Hi. Current UE Viewer build is 1101. Your version is 1021. It is quite possible that this is the core of your problem.
