### ISSUE TITLE
Redistribution permissions?

### ISSUE THREAD

**Issue by Mgamerz** [gildor2/UEViewer#138]
Hi Gildor,

I'm Mgamerz, current lead of the ME3Explorer toolset (https://github.com/me3tweaks/me3explorer). We've recently completely refactored our mesh code and our old psk exporting method was removed since it wasn't really compatible. Some users want to export things in PSK format, which UModel does (our new code is significantly different and would require a lot of work to implement again). I have tested and have found we would be able to use the command line options to automate export from within ME3Explorer's mesh tools.

I was wondering what permissions are on your project for redistribution since there isn't a license listed for UModel. We would either ship it with the ME3Explorer distribution or have it available to download on-demand from our repository's staticfiles directory, where we place optional executables we have tested against. The way our toolset works is that when a required optional executable/asset is required, it is downloaded and cached locally as necessary so we can keep the initial download smaller.

I could link against the one on your site, but I am not sure if the URL changes, and if it stays the same and you update the tool, users might receive a version we haven't tested against (I doubt you change CLI much if at all).

Thanks,
Mgamerz

**Comment by gildor2** [comment]
Hi,

I'm ok with redistribution, as soon as you'll keep readme.txt with it. Regarding links, the only persistent links are URLs of pages which holds the downloads (/projects/umodel and /downloads). The link to zip file is not persistent.

Thanks,
Konstantin

**Comment by Mgamerz** [comment]
Cool, thanks!
