### ISSUE TITLE
Conan Exiles error

### ISSUE THREAD

**Issue by Sn0wBiT** [gildor2/UEViewer#143]
I got this error when open Conan Exiles folder.

![image](https://user-images.githubusercontent.com/9019527/67353636-2c08c480-f57d-11e9-8b66-c9e1c2d495ab.png)

**Comment by gildor2** [comment]
UModel never opened Conan pak files. You should unpack it first, then open game files. Details are in Conan thread on the forum, link could be found in compatibility table.
