### ISSUE TITLE
Change "Browse for Folder" dialog to use different style

### ISSUE THREAD

**Issue by cmbasnett** [gildor2/UEViewer#145]
The current "Browse for Folder" dialog box when selecting the directory to use for the "Path to game files" is incredibly cumbersome and should be changed to the more standard File Browser dialog.

The File Browser dialog is much easier to navigate, has built-in support for copy-pasting paths, quick-access panel, favorites etc. that a user would expect in any other program.

Current
![image](https://user-images.githubusercontent.com/5035660/69112881-4461e700-0a36-11ea-808e-ff8de34d1cf0.png)

What it should be
![image](https://user-images.githubusercontent.com/5035660/69112966-770bdf80-0a36-11ea-8d8f-7d089739788c.png)

**Comment by gildor2** [comment]
Actually you can copy-paste paths and use autocompletion in path field left to the "Browse" button. The dialog which you see now is real "standard". Personally I like the way of seeing files and directories (what you propose) more, it's just much harder to implement - Windows has complex API for that.

**Comment by gildor2** [comment]
Done, https://github.com/gildor2/UEViewer/commit/2f810e29d666cd1d40705dbfbec8e4765a7bae84
