### ISSUE TITLE
Rocket League update 1.70 breaks the viewer

### ISSUE THREAD

**Issue by Longi94** [gildor2/UEViewer#147]
Rocket League 1.70 was released earlier today. Umodel fails to open new .upk files. Tried the following new files that fail:
* `body_durian_tier1_SF.upk`
* `body_durian_tier2_SF.upk`
* `body_durian_tier3_SF.upk`
* `skin_seasontwelve_SF.upk`

Old files seem to work fine. Maybe @AltimorTASDK has an idea.

```
umodel -game=rocketleague -path=D:\Steam\steamapps\common\rocketleague\TAGame\CookedPCConsole -export body_durian_tier1_SF.upk
Found 5399 game files (0 skipped) at path "D:/Steam/steamapps/common/rocketleague/TAGame/CookedPCConsole"
Scanned game directory in 0.2 sec, 11675 allocs, 0.00 MBytes serialized in 0 calls.
Loading package: body_durian_tier1_SF.upk Ver: 868/28 Engine: 10897 Names: 933 Exports: 443 Imports: 160 Game: 80004B
******** body_durian_tier1_SF.upk ********
*** ERROR: Memory: bad allocation size 744440720 bytes
appMalloc:size=744440720 (total=0 Mbytes) <- FArray::Empty:314963001 x 16 <- TArray::Serialize:0/0 <- UnPackage::ReplaceLoader <- UnPackage::UnPackage:body_durian_tier1_SF.upk, ver=868/28, game=rocketleague <- UnPackage::LoadPackage:body_durian_tier1_SF.upk <- Main:umodel_build=1079
```

Edit: I've updated to build 1141, same error.

**Comment by jayskibruv** [comment]
@Longi94 Hello! Did you ever find a workaround for this? Currently having the same issue.

**Comment by Longi94** [comment]
newer files use different encryption keys and UE Viewer only has one hard coded. I do not know what all the keys are.

**Comment by gildor2** [comment]
This game's support was contributed with pull request https://github.com/gildor2/UEViewer/pull/73
