### ISSUE TITLE
Cannot install on macOS?

### ISSUE THREAD

**Issue by AndreySitnikov** [gildor2/UEViewer#148]
I have installed BuildTools and Visual Studio, but I am still getting the error "Visual C++ not found". 
some screenshots:
<img width="630" alt="Снимок экрана 2019-12-28 в 4 05 51 PM" src="https://user-images.githubusercontent.com/39302455/71546167-ed7ff380-298b-11ea-9e32-1c9a7e666447.png">
<img width="616" alt="Снимок экрана 2019-12-28 в 4 06 50 PM" src="https://user-images.githubusercontent.com/39302455/71546175-0f797600-298c-11ea-91c2-8b755453ab20.png">
<img width="560" alt="Снимок экрана 2019-12-28 в 4 07 54 PM" src="https://user-images.githubusercontent.com/39302455/71546188-3637ac80-298c-11ea-9bf9-0b9e18ad8d48.png">

**Comment by gildor2** [comment]
build.sh script has this line:
```
[ "$OSTYPE" == "linux-gnu" ] || [ "$OSTYPE" == "linux" ] && PLATFORM="linux"
```
So, it recognizes linux this way. Otherwise it treats OS as Windows. Anyway, MacOS shouldn't work - I never had any access to Mac, so only 2 platforms are supported: Windows and Linux.

**Comment by AndreySitnikov** [comment]
ok :(

**Comment by gildor2** [comment]
Actually limited macOS support has been added in August 2020. Can't do more because I don't have a mac.
