### ISSUE TITLE
windows-vs2017-how to generateVS solution?

### ISSUE THREAD

**Issue by ahsanMuzaheed** [gildor2/UEViewer#150]
is there any way to generate VS solution so that i can edit and debug using VS?

**Comment by gildor2** [comment]
There's already a solution, use "open a local folder".

**Comment by ahsanMuzaheed** [comment]
thanks. that is what i am doing right now. although if i select UEViewer folder than Vs not including contents in UmodelTool folder. so i have to open "UEViewer\UmodelTool" folder.
problem is that i cant debug because there is no *.sln or *vcproj.

**Comment by gildor2** [comment]
Good catch, thanks. Seems fixed: https://github.com/gildor2/UEViewer/commit/f39d127fa18d95d2acc77a87fdd84ff5bd30028e
