### ISSUE TITLE
Texture & Materials Not Exported

### ISSUE THREAD

**Issue by DemonRem** [gildor2/UEViewer#151]
@gildor2 from some reason your tool only export the mesh not the texture and materials
this is the only things been found , UE version is 4.16
![2](https://user-images.githubusercontent.com/29927382/75886259-a05b4a80-5e30-11ea-96ea-ddf4585e7597.png)
![3](https://user-images.githubusercontent.com/29927382/75886268-a2250e00-5e30-11ea-9b84-bf0959131924.png)

![1](https://user-images.githubusercontent.com/29927382/75886256-9f2a1d80-5e30-11ea-8497-8e40c4dffa36.png)

![4](https://user-images.githubusercontent.com/29927382/75886458-eadcc700-5e30-11ea-9b56-4bfff030184c.png)

**Comment by gildor2** [comment]
There's no point to duplicate your forum questions at github
https://www.gildor.org/smf/index.php/topic,6070.msg35475.html#msg35475
