### ISSUE TITLE
UEViewer Linux - libpng12.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by 0Curtain0** [gildor2/UEViewer#152]
**UModel Linux Version:** 15 March, 2020 
**Operating System:** Manjaro Linux 19.0.2 (Kyria) 64-bit
**Game:** DC Universe Online 

**umodel** file is installed in the following directory: 
DC Universe Online / UNREAL3 / DCGAME / COOKEDPC /  

The following command was used in terminal:  
`./umodel CHARACTER/NPC/ICONIC/FACTIONAL/REDLANTERN/DCHRNPCICOFACRLN106.UPK`  

The following error was shown: 
`./umodel: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory`  

I opened Manjaro's software manager (Pamac) and searched for libpng: 

> **libpng** [extra]: A collection of routines used to create PNG format graphics files 
> **libpng12** [community]: A collection of routines used to create PNG format graphics files 
> **lib32-libpng** [multilib]: A collection of routines used to create PNG format graphics files (32-bit) 
> **lib32-libpng12** [multilib]: A collection of routines used to create PNG format graphics files 
> **png++** [community]: A C++ wrapper for libpng

It appears that Manjaro already has **libpng** and **lib32-libpng** installed. 
Do I need to install both **libpng12** and **lib32-libpng12** ? 

```
libpng12 (version 1.2.59-1)
http://www.libpng.org/pub/png/libpng.html 
Licenses: custom 
Repository: community 
Packager: Maxime Gauduin alucryd@archlinux.org 
Build Date: 03/06/2018 
Signatures: Yes
Depends On: glibc, zlib
``` 
```
lib32-libpng12 (version 1.2.59-1) 
http://www.libpng.org/pub/png/libpng.html 
Licenses: custom 
Repository: multilib 
Packager: Maxime Gauduin alucryd@archlinux.org 
Build Date: 03/06/2018 
Signatures: Yes 
Depends On: lib32-glibc, lib32-zlib
```

**Comment by gildor2** [comment]
Are you on 32 or 64-bit linux?

**Comment by 0Curtain0** [comment]
Sorry, I forgot to mention that it is 64-bit Linux.

**Comment by gildor2** [comment]
I see you're using MY build of UModel for linux. It was made for 32-bit system. So I suppose you don't have a 32-bit version of libpng installed on your system. Actually, I'd advise building umodel from source code, it shouldn't be hard for linux user (at least because the system won't require any additional setup) - just download and unpack source code zip, and run "build.sh".

**Comment by 0Curtain0** [comment]
> I see you're using MY build of UModel for linux. It was made for 32-bit system.  

I downloaded it from here: https://www.gildor.org/down/45/umodel/umodel_linux.tar.gz  
Did I download from the wrong place? 

> So I suppose you don't have a 32-bit version of libpng installed on your system. 

According to the software manager that comes with Manjaro Linux, I see both **libpng** and **lib32-libpng** already installed. 
Is **lib32-libpng** the 32-bit version you are talking about or do you mean **lib32-libpng12**? 

The error in the terminal mentioned something about libpng12.so.0. 

According to the software manager, both **libpng12** and **lib32-libpng12** are not installed.

**Comment by 0Curtain0** [comment]
> Actually, I'd advise building umodel from source code, it shouldn't be hard for linux user (at least because the system won't require any additional setup) - just download and unpack source code zip, and run "build.sh". 

I just tried this now and it works without issues. Thank you. 

However, out of curiousity, does installing **libpng12** and/or **lib32-libpng12** fix the error too?

**Comment by gildor2** [comment]
I suppose installing of 32-bit version of libpng should fix the issue, however I can't be sure, I'm not a powerful linux user.

**Comment by Blenux** [comment]
I just use the windows version in Wine, has slight issue with mouse grabbing with rotating in the viewport but works none the less.

**Comment by 0Curtain0** [comment]
@Blenux yea, I actually use it with Steam's Proton 5.0.5 which works like a charm, but I was also curious about the native linux development as well.

**Comment by gildor2** [comment]
Linux port of UModel doesn't have a UI.

**Comment by 0Curtain0** [comment]
@gildor2 yea, I sometimes switch between the Windows version and Linux version depending on when I need to do something quick or just browse leisurely. 

Any plans to incorporate some type of UI for the Linux port in the future? 
Nothing urgent, since Wine/Proton has been amazing on Linux. Maybe someone in the Linux community might want to try replicating or creating a brand new one just for fun or practice.

**Comment by gildor2** [comment]
Plans - yes, sure. However it's a huge amount of work, which most likely won't be interruptable (e.g. with other UModel work, or even with my primary job), so I just don't have a time for that.
