### ISSUE TITLE
Older code from the tool

### ISSUE THREAD

**Issue by kingofthebongo2008** [gildor2/UEViewer#153]
Hello, some people asked me to recover old assets for their unreal data.
They have supplied to me this tool as a binary from 2012 and said it was working,
Do you have by chance code from that time ?

**Comment by gildor2** [comment]
If you've registered at GitHub, you SHOULD know what "git" is.
https://github.com/gildor2/UEViewer/commits/master

**Comment by kingofthebongo2008** [comment]
Hello,
The oldest code i have found was from 2014.
So you say, 2011-2012 is there also, right?

**Comment by kingofthebongo2008** [comment]
You did a good job for this tool, i guess it was helpful for many people

**Comment by gildor2** [comment]
Example: September 2007
![image](https://user-images.githubusercontent.com/7008904/79846588-ad77cd00-83cf-11ea-9c93-1ecdbf5922da.png)

**Comment by kingofthebongo2008** [comment]
Great, thank you,
It was my mistake
