### ISSUE TITLE
Default path value should use current working directory

### ISSUE THREAD

**Issue by cmbasnett** [gildor2/UEViewer#154]
When invoking umodel from the command-line (I'm on Ubuntu), the default path appears to default to the user's home directory instead of the current working directory. This behavior breaks convention with most other software that uses the current working directory as the default.

# What happens
```
> pwd
/home/colin/.local/share/Steam/steamapps/common/Red Orchestra
> umodel -path="."
*** ERROR: Too many unknown files - bad root directory (/home/colin/.)?
appRegisterGameFile:/home/colin/./grf-python2/data/sprite/아이템/장군의투구.spr <- ScanGameDirectory <- ScanGameDirectory <- ScanGameDirectory <- ScanGameDirectory <- ScanGameDirectory <- appSetRootDirectory:dir=/home/colin/. <- Main:umodel_build=1184
```

On top of the behavior above (explicitly giving the relative "this" directory to path), failing to provide a `path` argument similarly assumes that `path` is `~`, at least on Linux.

# What should happen
The default value of `path` should be the current working directory.

**Comment by gildor2** [comment]
I intentionally used HOME at linux, Actually I'm unsure how it should work - where to pick .cfg file, where to store extracted files, where to pick upk/uasset files if relative path is provided. May be more people could join the discussion?

**Comment by Blenux** [comment]
Hmmm I don't use the Linux Build of uModel, since I like to see the models in a GUI and plus I always get the libpng12.so.0 error, using it under Wine with the Windows Build has the default location of where the umodel.exe is located.
![Screenshot from 2020-05-02 16-07-51](https://user-images.githubusercontent.com/25260650/80856662-193f1d00-8c8f-11ea-906f-4491a6f0bdd2.png)

**Comment by cmbasnett** [comment]
The configuration file would presumably be stored either alongside the executable itself or inside the user's path, the latter being the better option. I was under the impression that the `-path` value was more of a hint for where the base game directory was, not where to find the program configuration.It sounds like the `path` value is being used for both of these, though I'm not familiar with how it's all set up in umodel under the hood, though.

If this is the case, I would suggest making a distinction between configuration directory and the root "game" directory, as it would decouple program configuration from the transient session-level game root directory.

**Comment by gildor2** [comment]
The issue should be fixed now. -path option will explicitly use CWD as a base when relative path is used. The issue has been closed automatically with commit message (I didn't expect that), so reopen it if needed.

**Comment by cmbasnett** [comment]
Thanks so much!
