### ISSUE TITLE
How to stop it from closing when there's a fatal error?

### ISSUE THREAD

**Issue by umustbeloggedintododat** [gildor2/UEViewer#156]
It always closes when there's a fatal error, causing me to restart and configure the settings again. I don't wait that. Any way?

**Comment by gildor2** [comment]
Make a batch file, put all settings to the command line. Then if error, you'll just run the batch again, without configuring anything.

**Comment by umustbeloggedintododat** [comment]
Sorry, I'm not into that batch settings stuff. How would I do this?

**Comment by gildor2** [comment]
Sorry, I don't have any links to tutorials about batch files.

**Comment by umustbeloggedintododat** [comment]
That's a shame. Can you at least show a list of the commands for launching it?

**Comment by gildor2** [comment]
umodel.exe -game=[something] -path=[path to files]
Add -nomesh, -nostat, -noanim, -notex - to disable skeletal meshes, static meshes. animations or textures - if umodel crashes with them.

**Comment by umustbeloggedintododat** [comment]
What's the name of Rocket League? I would like to know.

**Comment by gildor2** [comment]
-game=rocketleague
However there could be problems with this game, it seems the compatibility was lost some time ago
https://www.gildor.org/smf/index.php/topic,6957.0.html

**Comment by umustbeloggedintododat** [comment]
Thanks I made a batch file.

Also all models have some sort of grid texture on them and not the actual texture. What is going on?

**Comment by gildor2** [comment]
https://www.gildor.org/projects/umodel/faq#Texturing-questions
