### ISSUE TITLE
open ue424 crash

### ISSUE THREAD

**Issue by gituser1024** [gildor2/UEViewer#158]
when double click 
ShooterGame\Content\Characters\HeroFPP\HeroFPP.uasset

**Comment by gituser1024** [comment]
i see,it's a good job if also run on editor asserts.

**Comment by gildor2** [comment]
Yeah, I know. I'm working on that, but always interrupted with something else.

**Comment by FabianFG** [comment]
ShooterGame is Valorant so it should be cooked

**Comment by gildor2** [comment]
ShooterGame is a free example at Epic Games Store. I use it myself for testing UModel's compatibility with new engine stuff.

**Comment by FabianFG** [comment]
Oh then Valorant uses the same name, sorry

**Comment by gildor2** [comment]
Some UE3 games has "UDKGame" folder inside. It just depends on laziness/business of developers. Valorant devs used ShooterGame as a base and didn't get rid of that folder yet.
