### ISSUE TITLE
Mortal Kombat 11 Support

### ISSUE THREAD

**Issue by thethiny** [gildor2/UEViewer#160]
Hello,
I'm working on Mortal Kombat 11 Support and I'm able to extract all the data without proper names and without the extra PSF files. Would you be interested in incorporating it into your tools?

**Comment by gildor2** [comment]
Hi
Were you able to extend UE Viewer with getting models from this game?

**Comment by Blenux** [comment]
Just note 

> NetherRealm Studios’ Programming Lead Jon Greenberg has taken the matter in his own hands and clarified that the game indeed is not running on Epic’s Unreal Engine 4, rather it is built on NetherRealms custom version of Unreal Engine 3. Also adding that their custom engine is radically different from Epics UE4.

**Comment by thethiny** [comment]
@gildor2 I didn't extend UEViewer, I currently have the code as a separate program, and I'm in the process of documenting everything along the way. I was hoping that if you're interested in incorporating the method into your program since MK11 works similarly to UE3 and UE4.

@Blenux yes, I'm aware of this but after extracting the files and looking into it, the engine is technically still the same underneath.

For MK11, the game still utilizes the same import/export/name tables format but instead of being part of the header they're part of a package called Header Data that uses Oodle Kraken. The rest is the same as Mortal Kombat X which is working with UEViewer.

**Comment by Blenux** [comment]
That's good then, wanted to check the models out for this game but no one had tools for it, and I have no idea how to work stuff like this out lol.

**Comment by thethiny** [comment]
Here's a tool for extracting models made by someone else.
https://zenhax.com/viewtopic.php?t=11359

**Comment by gildor2** [comment]
There are many reasons why I didn't support MK11 (UE3 version) in UModel, and they're still valid
1. Oodle - I've added oodle decompressor for new Star Wars game (IMO it's more valuable than another-one-MK), however it is buggy and I can't rely on it. I had to integrate some workarounds to avoid crashes with one of assets. I've reported a bug to the library author, however I doubt it will be fixed one day, as author even didn't respond to my message. Kraken dll is not considered for integration.
2. The game has UE4 version which is supported, even with animation.
3. There's another tool mentioned above which can do the job.
4. The game has too large difference from original engine, which makes extremely hard to integrate anything into UE Viewer. It's much easier to make a separate tool for that (which is already exists).
5. Lack of time for doing such amount of work for just a single game.

**Comment by thethiny** [comment]
@gildor2 Okay, I support your decision. And thank you for your reply!
I've seen your issue on @powzix/ooz and I too face some issues with his library, however there is a workaround for the Star Wars (and potential oodle) games. You can ask the user to specify the oodle dll and just link to the decompress function used in it. This will be more stable and will work on every game, since every game needs its own oodle dll.

**Comment by gildor2** [comment]
As I said, dll is not the solution - it will work only for Windows, and people will spam on the forum, github, facebook or youtube asking me "where can I get the dll". Anyway, the problem seems happened only with one useless texture, so I decide not to do anything more complex.

**Comment by thethiny** [comment]
There is another method if you don't want to utilize the dll, as seen by https://github.com/AltimorTASDK/dfpslayer/blob/master/main.cpp.
The author of that repo simply utilizes the assembly code of the program and marks it as code segment to allow execution.

I don't want to bother you more with this discussion as I understand that you've already made up your mind, so I will close this issue now. Thank you gildor for all the work you've put in your UE viewer, tons of respect to you!

**Comment by gildor2** [comment]
> There is another method if you don't want to utilize the dll, as seen by https://github.com/AltimorTASDK/dfpslayer/blob/master/main.cpp.
> The author of that repo simply utilizes the assembly code of the program and marks it as code segment to allow execution.
Interesting approach, however
1. it's totally not cross-platform (even between 32 and 64 bit builds)
2. won't work for complex algorithm, e.g. for oodle
3. even if it would work, it would require locating and stripping decompression code, all of related data tables etc in assembly level.

**Comment by thethiny** [comment]
Thank you again @gildor2!
