### ISSUE TITLE
Will you add support for Train Sim World 2020?

### ISSUE THREAD

**Issue by UP5468-GE-ES44AC** [gildor2/UEViewer#161]
Few days ago,I mentioned this game in forum but no one reply. So I just ask, will you add support
for TSW 2020?

Currently Umodel can view & export TSW 2020's StaticMesh ,Textures. SkeletalMesh and Animation will crash the Umodel.

**Comment by gildor2** [comment]
Not planned. It was enough to mention the game on the forum, github issues exists for different purpose.

**Comment by gildor2** [comment]
Sorry, but this game is not the one which "definitely should be supported". Usually UE4 games are either work without any additional work in UModel, or something doesn't work. I'm doing special stuff only for most significant titles.

**Comment by UP5468-GE-ES44AC** [comment]
> Sorry, but this game is not the one which "definitely should be supported". Usually UE4 games are either work without any additional work in UModel, or something doesn't work. I'm doing special stuff only for most significant titles.

Ok,I see.Thank you for your reply.
