### ISSUE TITLE
fortnite, cannot import a skin

### ISSUE THREAD

**Issue by geekn00b** [gildor2/UEViewer#162]
******** Loading object SkeletalMesh4'M_MED_Racer_Zero_Mask.M_MED_Racer_Zero_Mask' ********

ERROR: Serialized FString is not null-terminated
FString<< <- TArray::Serialize:0/1 <- FSkinWeightProfilesData<< <- FStaticLODModel4::SerializeStreamedData <- FStaticLODModel4::SerializeRenderItem <- TArray::Serialize:3/4 <- USkeletalMesh4::Serialize <- LoadObject:SkeletalMesh4'M_MED_Racer_Zero_Mask.M_MED_Racer_Zero_Mask', pos=477B3, ver=519/0 (unversioned), game=ue4.26 <- UObject::EndLoad <- LoadWholePackage:M_MED_Racer_Zero_Mask <- CUmodelApp::ShowPackageUI <- CUmodelApp::ProcessKey:key=6F, down=1 <- VisualizerLoop <- Main:umodel_build=1216

**Comment by gildor2** [comment]
https://twitter.com/UGildor/status/1273563985896443904
