### ISSUE TITLE
A question about bulk data

### ISSUE THREAD

**Issue by thethiny** [gildor2/UEViewer#163]
Hello Gildor,
I have a question regarding bulk data and additional packages. Do you know how to map the bulk data and the additional packages to the export table? I've been trying for a while and I only noticed that there are some bytes shared between the bulk data and the additional data but I can't map it to the export table. I'm trying to build MK11 extraction but I'm stuck at this point.
Thank you

**Comment by gildor2** [comment]
Hi,
There are not "mappable". Bulk is always referenced by FBulkData structures (FByteBulkData etc) which are stored inside UObject's  data.

**Comment by thethiny** [comment]
Can I find this reference inside the Export Table?

**Comment by gildor2** [comment]
Are you sure you're familiar with object serialization in UE? Export table and import table are parts of _package_ data, and knows nothing about UObject. Export table _points_ to UObject data. Bulk therefore is pointed by UObject data, _package_ knows nothing about that.

**Comment by thethiny** [comment]
I'm not 100% familiar with UE, I'm learning, that's why I'm asking you. I was able to extract all the data I needed but I wasn't able to reference the bulk data. When I say "map" I mean point to.
Thank you for this information gildor!

**Comment by gildor2** [comment]
Well, bulk is usually used for texture and audio data (unless you're talking about recent UE4 versions). So, just to get a reference to some bulk, you should

1. read package export table
2. find a Texture2D object there
3. seek package to the object's location
4. fully serialize (some people say "deserialize") UTexture2D object, with all mipmaps
5. mipmaps will contain FByteBulkData objects inside, which are "headers" for a bulk
6. when engine wants to get texture data, it will use that FByteBulkData structure to find a bulk file, seek to relevant position and read texture data from it.

I'd recommend reading UModel's code if you want more details. I see you're working on MK11 project - this game is not supported in UModel. However you'll get some ideas about how it works in UE3 and UE4.

**Comment by FabianFG** [comment]
Once you try to implement a few export classes like UTexture2D you will learn how bulk data works

**Comment by thethiny** [comment]
@gildor2 thank you, very useful! I will look into that.

@FabianFG Will do, thanks.
