### ISSUE TITLE
Cannot compile on linux

### ISSUE THREAD

**Issue by arun54321** [gildor2/UEViewer#166]
I get errors.

https://del.dog/vupawocude.txt

Distro: Arch Linux.

**Comment by gildor2** [comment]
- compiler + its version
- platform (Intel 32/64 etc)

**Comment by arun54321** [comment]
gcc (GCC) 10.1.0
intel 64 bits.

**Comment by gildor2** [comment]
This is a strange thing, perhaps some regression in compiler. I'm not supplying "-Wnarrowing" option to gcc's command line, but it is processing that, and even more - throws a fatal error with it.

I'd suggest upgrading to 10.2.0 which was released recently. Personally I'm building UModel with gcc 7.4.0 (older Linux Mint, 32 bit).

The same is here: https://bugzilla.redhat.com/show_bug.cgi?id=1803333
I think this is a regression in compiler, because a) I didn't enable this warning, b) the warning appears as error, c) it didn't appear before, d) it doesn't appear with recent Visual Studio

**Comment by gildor2** [comment]
Well, I've performed some tests with "Compiler Explorer", it seems clags has the same warning. So I've decided to fix it, without updating the compiler myself - i.e. with using your error logs.
https://github.com/gildor2/UEViewer/commit/2472fcdee8141c4a031441c30e2119794b02080a

Please verify on your side and let me know if it's enough or not.

**Comment by arun54321** [comment]
Generating makefile from UmodelTool/umodel.project ...
Memory.cpp
Parallel.cpp
UmodelApp.cpp
UmodelCommands.cpp
Core/Memory.cpp: In function ‘void* appMalloc(int, int, bool)’:
Core/Memory.cpp:213:44: error: no matching function for call to ‘InterlockedAdd(size_t*, int&)’
  213 |  InterlockedAdd(&GTotalAllocationSize, size);
      |                                            ^
In file included from Core/Memory.cpp:2:
Core/Parallel.h:246:19: note: candidate: ‘int32 InterlockedAdd(volatile int64*, int64)’ (near match)
  246 | FORCEINLINE int32 InterlockedAdd(volatile int64* Value, int64 Amount)
      |                   ^~~~~~~~~~~~~~
Core/Parallel.h:246:19: note:   conversion of argument 1 would be ill-formed:
Core/Memory.cpp:213:17: error: invalid conversion from ‘size_t*’ {aka ‘long unsigned int*’} to ‘volatile int64*’ {aka ‘volatile long long int*’} [-fpermissive]
  213 |  InterlockedAdd(&GTotalAllocationSize, size);
      |                 ^~~~~~~~~~~~~~~~~~~~~
      |                 |
      |                 size_t* {aka long unsigned int*}
In file included from Core/Memory.cpp:2:
Core/Parallel.h:251:19: note: candidate: ‘int32 InterlockedAdd(volatile uint64*, int64)’ (near match)
  251 | FORCEINLINE int32 InterlockedAdd(volatile uint64* Value, int64 Amount)
      |                   ^~~~~~~~~~~~~~
Core/Parallel.h:251:19: note:   conversion of argument 1 would be ill-formed:
Core/Memory.cpp:213:17: error: invalid conversion from ‘size_t*’ {aka ‘long unsigned int*’} to ‘volatile uint64*’ {aka ‘volatile long long unsigned int*’} [-fpermissive]
  213 |  InterlockedAdd(&GTotalAllocationSize, size);
      |                 ^~~~~~~~~~~~~~~~~~~~~
      |                 |
      |                 size_t* {aka long unsigned int*}
Core/Memory.cpp: In function ‘void* appRealloc(void*, int)’:
Core/Memory.cpp:273:48: error: no matching function for call to ‘InterlockedAdd(size_t*, int)’
  273 |  InterlockedAdd(&GTotalAllocationSize, -oldSize);
      |                                                ^
In file included from Core/Memory.cpp:2:
Core/Parallel.h:246:19: note: candidate: ‘int32 InterlockedAdd(volatile int64*, int64)’ (near match)
  246 | FORCEINLINE int32 InterlockedAdd(volatile int64* Value, int64 Amount)
      |                   ^~~~~~~~~~~~~~
Core/Parallel.h:246:19: note:   conversion of argument 1 would be ill-formed:
Core/Memory.cpp:273:17: error: invalid conversion from ‘size_t*’ {aka ‘long unsigned int*’} to ‘volatile int64*’ {aka ‘volatile long long int*’} [-fpermissive]
  273 |  InterlockedAdd(&GTotalAllocationSize, -oldSize);
      |                 ^~~~~~~~~~~~~~~~~~~~~
      |                 |
      |                 size_t* {aka long unsigned int*}
In file included from Core/Memory.cpp:2:
Core/Parallel.h:251:19: note: candidate: ‘int32 InterlockedAdd(volatile uint64*, int64)’ (near match)
  251 | FORCEINLINE int32 InterlockedAdd(volatile uint64* Value, int64 Amount)
      |                   ^~~~~~~~~~~~~~
Core/Parallel.h:251:19: note:   conversion of argument 1 would be ill-formed:
Core/Memory.cpp:273:17: error: invalid conversion from ‘size_t*’ {aka ‘long unsigned int*’} to ‘volatile uint64*’ {aka ‘volatile long long unsigned int*’} [-fpermissive]
  273 |  InterlockedAdd(&GTotalAllocationSize, -oldSize);
      |                 ^~~~~~~~~~~~~~~~~~~~~
      |                 |
      |                 size_t* {aka long unsigned int*}
Core/Memory.cpp: In function ‘void appFree(void*)’:
Core/Memory.cpp:320:55: error: no matching function for call to ‘InterlockedAdd(size_t*, int)’
  320 |  InterlockedAdd(&GTotalAllocationSize, -hdr->blockSize);
      |                                                       ^
In file included from Core/Memory.cpp:2:
Core/Parallel.h:246:19: note: candidate: ‘int32 InterlockedAdd(volatile int64*, int64)’ (near match)
  246 | FORCEINLINE int32 InterlockedAdd(volatile int64* Value, int64 Amount)
      |                   ^~~~~~~~~~~~~~
Core/Parallel.h:246:19: note:   conversion of argument 1 would be ill-formed:
Core/Memory.cpp:320:17: error: invalid conversion from ‘size_t*’ {aka ‘long unsigned int*’} to ‘volatile int64*’ {aka ‘volatile long long int*’} [-fpermissive]
  320 |  InterlockedAdd(&GTotalAllocationSize, -hdr->blockSize);
      |                 ^~~~~~~~~~~~~~~~~~~~~
      |                 |
      |                 size_t* {aka long unsigned int*}
In file included from Core/Memory.cpp:2:
Core/Parallel.h:251:19: note: candidate: ‘int32 InterlockedAdd(volatile uint64*, int64)’ (near match)
  251 | FORCEINLINE int32 InterlockedAdd(volatile uint64* Value, int64 Amount)
      |                   ^~~~~~~~~~~~~~
Core/Parallel.h:251:19: note:   conversion of argument 1 would be ill-formed:
Core/Memory.cpp:320:17: error: invalid conversion from ‘size_t*’ {aka ‘long unsigned int*’} to ‘volatile uint64*’ {aka ‘volatile long long unsigned int*’} [-fpermissive]
  320 |  InterlockedAdd(&GTotalAllocationSize, -hdr->blockSize);
      |                 ^~~~~~~~~~~~~~~~~~~~~
      |                 |
      |                 size_t* {aka long unsigned int*}
make: *** [obj/umodel-linux.mak:1485: obj/umodel-unix/Memory.o] Error 1
make: *** Waiting for unfinished jobs....
Core/Parallel.cpp: In constructor ‘CSemaphore::CSemaphore()’:
Core/Parallel.cpp:172:29: error: static assertion failed: Review SemSize
  172 |  static_assert(sizeof(data) >= sizeof(sem_t), "Review SemSize");
      |                ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
make: *** [obj/umodel-linux.mak:1489: obj/umodel-unix/Parallel.o] Error 1

**Comment by gildor2** [comment]
Added this:
https://github.com/gildor2/UEViewer/commit/e7e67c505d3e305d03f4caeaadd037b6298c81ee

Please try again.

**Comment by arun54321** [comment]
Generating makefile from UmodelTool/umodel.project ...
ExportTexture.cpp
PackageUtils.cpp
TypeInfo.cpp
UnCore.cpp
In file included from Exporters/ExportTexture.cpp:3:
./Core/Core.h:164:21: error: conflicting declaration ‘typedef int64_t int64’
  164 | typedef int64_t     int64;
      |                     ^~~~~
In file included from ./libs/nvtt/nvcore/nvcore.h:160,
                 from ./libs/nvtt/nvcore/Debug.h:6,
                 from ./libs/nvtt/nvimage/Image.h:6,
                 from ./Unreal/Wrappers/TextureNVTT.h:4,
                 from Exporters/ExportTexture.cpp:1:
./libs/nvtt/nvcore/DefsGnucLinux.h:62:29: note: previous declaration as ‘typedef long long int int64’
   62 | typedef signed long long    int64;
      |                             ^~~~~
In file included from Exporters/ExportTexture.cpp:3:
./Core/Core.h:165:21: error: conflicting declaration ‘typedef uint64_t uint64’
  165 | typedef uint64_t    uint64;
      |                     ^~~~~~
In file included from ./libs/nvtt/nvcore/nvcore.h:160,
                 from ./libs/nvtt/nvcore/Debug.h:6,
                 from ./libs/nvtt/nvimage/Image.h:6,
                 from ./Unreal/Wrappers/TextureNVTT.h:4,
                 from Exporters/ExportTexture.cpp:1:
./libs/nvtt/nvcore/DefsGnucLinux.h:61:29: note: previous declaration as ‘typedef long long unsigned int uint64’
   61 | typedef unsigned long long  uint64;
      |                             ^~~~~~
make: *** [obj/umodel-linux.mak:913: obj/umodel-unix/ExportTexture.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by gildor2** [comment]
https://github.com/gildor2/UEViewer/commit/ccb4a580bf5bc67d254d38679e67faaf0c8e6b8d

**Comment by arun54321** [comment]
./build.sh                                                        
Generating makefile from UmodelTool/umodel.project ...
Parallel.cpp
PackageDialog.cpp
PackageScanDialog.cpp
ProgressDialog.cpp
SettingsDialog.cpp
StartupDialog.cpp
UmodelApp.cpp
UmodelCommands.cpp
UmodelSettings.cpp
Core/Parallel.cpp: In constructor ‘CSemaphore::CSemaphore()’:
Core/Parallel.cpp:172:29: error: static assertion failed: Review SemSize
  172 |  static_assert(sizeof(data) >= sizeof(sem_t), "Review SemSize");
      |                ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
make: *** [obj/umodel-linux.mak:1489: obj/umodel-unix/Parallel.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by gildor2** [comment]
https://github.com/gildor2/UEViewer/commit/f510431f17036e9f15d62272e9363219c8b42268

**Comment by arun54321** [comment]
It compiles without any errors now.

**Comment by gildor2** [comment]
Cool!
