### ISSUE TITLE
Is there any way to read the widgets' name from a widgetblueprint.uasset

### ISSUE THREAD

**Issue by AiMizuno** [gildor2/UEViewer#167]
Hi, I am learning how UE4 serializes and want to make a plugin to compare two UMG blueprints. I notice umodel only counts widgets.  Can umodel also get the name by modifying LoadPackage? Thank you.

**Comment by gildor2** [comment]
Hi. UModel is "model" viewer, it is not intended to read widgets neither now nor in the future.

**Comment by AiMizuno** [comment]
Well. Maybe my english is poor. I have suffered from loading a uasset outside the project for a few days and your code teaches me a lot, so I wonder whether I can know how to read widgets from the code. And I would be grateful if you can provide some ideas. Thanks.

**Comment by gildor2** [comment]
Well ... UI in UE4 is constructed either from C++ code (with use of Slate module), or with use of WidgetBlueprint. Blueprint asset consist mainly from "Construction Script" which is used to instantiate it at runtime when needed. I'm not aware of how Construction Script structured, how it is serialized and so on, so I can't help you with this.

**Comment by AiMizuno** [comment]
Thank you so much. I think I should learn from the Engine source code to make it clear.
