### ISSUE TITLE
ERROR: Memory: bad allocation size 1774379351 bytes

### ISSUE THREAD

**Issue by Bluscream** [gildor2/UEViewer#169]
```
ERROR: Memory: bad allocation size 1774379351 bytes
appMalloc:size=1774379351 (total=0 Mbytes) <- FArray::Empty:1774379351 x 1 <- FString<< <- SerializePackageFileSummary3 <- FPackageFileSummary<<:Ver=1809/0 <- UnPackage::UnPackage:CombatGame/CookedPC/025e2f5588a72e740.upk, ver=1809/0, game=ue3 <- UnPackage::LoadPackage:CombatGame/CookedPC/025e2f5588a72e740.upk <- CUmodelApp::ShowPackageUI <- Main:umodel_build=975
```

**Comment by gildor2** [comment]
#113

**Comment by Bluscream** [comment]
Just acknowledge that you gave up on this project xD i used the right settings

**Comment by gildor2** [comment]
When you're asking for help, you AT LEAST should provide the name of the game. Copy-pasting the error message just acknowledges that you're too lazy to compose error report yourself. You didn't put any word yourself.

And - the topic I mentioned in my reply has much more that just "incorrect settings", e.g. saying - when you shouldn't use github issues, but use forum instead.

**Comment by Bluscream** [comment]
Black Squad is the name of the game, and it runs on UE3.

**Comment by gildor2** [comment]
This game has encrypted upk files, it is not supported.

**Comment by Bluscream** [comment]
Oh wow, would be nice if the error message would just show that. Doesnt fortnite also have encrypted assets?

**Comment by gildor2** [comment]
Error message just says that UModel can't load something. UModel doesn't know why does this happen.
Regarding Fortnite, there's a thread on the forum, and dedicated thread regarding encryption key.
https://www.gildor.org/smf/index.php/board,38.0.html

**Comment by Bluscream** [comment]
So that means i should be able to open Black Squad files when i find their encryption key?

**Comment by gildor2** [comment]
Nope. This means that upk files uses custom encryption, so it is not possible to reverse engineer upk format to add support.
