### ISSUE TITLE
Re-select UE4 version without closing program?

### ISSUE THREAD

**Issue by Toshiba1127** [gildor2/UEViewer#171]
I'm dealing with unversioned UE4 games and trying all versions until extracting work, but I have to close the program and open again to select UE4 version

Is it possible to re-select version without closing the program, maybe add it under "tools" button? just a thought

**Comment by gildor2** [comment]
No way. This would require architectural changes in UModel.

**Comment by Toshiba1127** [comment]
Ok, that's fine
