### ISSUE TITLE
program crash

### ISSUE THREAD

**Issue by wOo00w** [gildor2/UEViewer#173]
Hey bro,I got an issue here,I use UEViewer opend a pak file and randomly choosed an UE4 version for I don't know the true version is,the I double clicked a mesh,then it shows the follow error which I don't know what it is.
![2020-09-24 104354](https://user-images.githubusercontent.com/4704300/94095106-96904780-fe53-11ea-9d85-5c9d695a8371.png)

Files attached below.
thanks a lot 

[AK47.zip](https://github.com/gildor2/UEViewer/files/5273145/AK47.zip)

**Comment by Blenux** [comment]
This should be on the forum rather then here.

And what game your trying to get this from?

**Comment by wOo00w** [comment]
thanks bro,I just check the issues, right,here is not a good palce,I'll closed it then ;)
