### ISSUE TITLE
Exporting CameraAnim

### ISSUE THREAD

**Issue by rickypai** [gildor2/UEViewer#175]
Hi,

I'm interested in exporting [CameraAnims](https://docs.unrealengine.com/en-US/Gameplay/Framework/Camera/Animations/index.html) to edit them in mods.

It seems like UEViewer is able to infer the asset's class but not export them. I'm wondering whether it would be possible (and how hard it would be) to do this. I'm new to C++ but have decent experience in programming. If you can share some pointers, I'd be happy to give implementing this a try.

Thank you,

**Comment by gildor2** [comment]
Hi,
I never looked at camera animations, but I think this would be a part of matinee stored as curves, which are supported only with fbx format. So, it is not possible to do with UModel.
Also, digging into matinee is a big pain.

**Comment by rickypai** [comment]
Thanks for the prompt response. Seems like incorporating it into with UModel would be a big pain.

Another way I was thinking is that perhaps I can use some part of UModel (in my own build) to decode the coordinates of each keyframe to something primitive like csv, then I can write scripts to translate the keyframes into another 3D program. Do you think just getting the coordinates of each frame would be difficult?

**Comment by gildor2** [comment]
I really don't know, the answer would require me to heavily inspect UE code in the areas where I'm not familiar.
