### ISSUE TITLE
i have this error can help  me please 

### ISSUE THREAD

**Issue by santiago899** [gildor2/UEViewer#177]
I am using umodel for fortnite is the new version that is in the patreon Memory: bad allocation size -1717559264 bytes
appMalloc: size=-1717559264 (total=95 Mbytes) <- FArray::Empty: -858980095 x 32 <- TArray::Serialize: 0/0 <- USkeletalMesh4::Serialize <- LoadObject: SkeletalMesh4'F_MED_AshtonBoardwalk.F_MED_AshtonBoardwalk', pos=162D, ver=521/0, game=ue4.26 <- UObject::EndLoad <- LoadWholePackage: /Game/Characters/Player/Female/Medium/Bodies/F_MED_AshtonBoardwalk/Meshes/F_MED_AshtonBoardwalk.uasset <- CUmodelApp::ShowPackageUI <- Main: umodel_build=1454

**Comment by gildor2** [comment]
#113
