### ISSUE TITLE
Audio export doesn't work.

### ISSUE THREAD

**Issue by ghGYR** [gildor2/UEViewer#182]
I  have checked the audio support,  but It  always shows "Exported 0/0 objects in 0.0 sec". What's the reason?

**Comment by gildor2** [comment]
Many reasons. For instance, readme says that sounds should be explicitly enabled - not everyone follows that. Also you may point at upk/uasset which doesn't have sounds inside (despite it may have "sound" it its name). And finally, sounds could be prepared with use of WWise or different third-party audio library.
