### ISSUE TITLE
using on mac as command line exporter utility

### ISSUE THREAD

**Issue by sorrowsin** [gildor2/UEViewer#183]
how would i go about using UEViewer as command line exporter utility? When running ./build.sh in the UEViewer-master folder, the following error appears "ERROR: can't open infile UmodelTool/umodel.project". I dont know if i am going about this right, as when investigating why umodel.project could not be opened, it did not look like there support for other OS. I understand that you do not have a mac therefore making it harder to make it compatible, but i just wasn't sure if i was trying run it as a command line exporter utility the wrong way

**Comment by gildor2** [comment]
You're not running the exporter with your steps, you're about to build (compile) it.  Are you using command line (bash) or something else, e.g. running build.sh with some GUI? The workflow it typical for Unix systems:
- open bash
- 'cd' to the directory where buils.sh exists (root UE Viewer source code directory)
- type './build.sh' and press 'Enter'

After that, if you have compilers (clang + gcc wrapper) installed, you'll get a file 'umodel' (I don't remember about the file's extension) next to the build.sh, it should be ready to run.

**Comment by sorrowsin** [comment]
i am using command line (terminal). I cd to where the UEViewer-master is, do 'ls' to make sure everything is there, then when i run the command './build.sh' and press enter, this is the error is get 

./build.sh: line 70: UmodelTool/Version.h: No such file or directory
./build.sh: line 107: Unreal/Shaders/make.pl: No such file or directory
Generating makefile from UmodelTool/umodel.project ...
ERROR: can't open infile UmodelTool/umodel.project
./obj/umodel-osx.mak:2: *** [GENMAKE ERROR] can't open infile UmodelTool/umodel.project.  Stop.

i was able to fix the first two errors by going into build.sh and changing the version_file variable to 'UI/UmodelTool/Version.h' instead of just 'UmodelTool/Version.h'. After the first two errors, i do not know how to fix it.

**Comment by gildor2** [comment]
It just appears to me like bash operates in a different directory. For instance, you may add 2 commands in the beginning of the build.sh file:

    pwd
    ls

It will print the current directory to console and list its contents. Or alternatively, you have nothing in the current directory except the build.sh file?

**Comment by sorrowsin** [comment]
are you asking if the build.sh is the only one in the directory? Cause i have the build.sh in with all of the other files. Are there any other libs/files incompatible with macOS that could be trying to be built, or you do think this is a directory/location issue? If you did not have time to look at the error file this is what it says

#----------------------------------------
$(error [GENMAKE ERROR] cannot find file "UnCore.h" included from "Main.cpp", directories used: [. ../../Core ../../Unreal ../../libs/include ../../libs ../../libs/nvtt /usr/include/libpng ../../libs/PowerVR ../../libs/detex ../../libs/rijndael])
#----------------------------------------

From the looks of it, there was an error finding the files. You said it looks like bash operates in a different directory so maybe this is it. do you think we need to add more support for mac in the shell script?

**Comment by gildor2** [comment]
I did compile the umodel for Mac with no problems, a few months ago. The build system didn't change after that. I've got the problems only when I mapped Windows drive to MacOS (via WMWare) and tried to build the project which was located there - it didn't work, I've got random compile errors. When I copied the full project to MacOS file system, things worked perfectly.

I believe there are also other people who did compile the UE Viewer for MacOS without problems, so I think this is your local issue. I've asked you to add 2 commands to the build.sh and check their results, but you didn't do that. Probably you can record a video showing what you're doing, it might provide me some ideas about what's wrong on your side?

**Comment by sorrowsin** [comment]
i edited my previous comment to include the commands, sorry

**Comment by sorrowsin** [comment]
ehhh, thats ok. Thank you very much for helping. My computer is 10 years old and i am getting a new one soon. im just gonna give up lol. Ive spent too much time with my computers incompatibilities. Have a good day

**Comment by gildor2** [comment]
It's worth checking the versions of bash and perl you have installed. Use

    bash --version
    perl --version

**Comment by sorrowsin** [comment]
bash verion - 

GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
Copyright (C) 2007 Free Software Foundation, Inc.

perl verions - 

This is perl 5, version 18, subversion 4 (v5.18.4) built for darwin-thread-multi-2level

**Comment by gildor2** [comment]
With 10 years old computer, you'd probably have an issue with too old clang anyway. I'm using C++17 capabilities I think.

**Comment by sorrowsin** [comment]
wow, i think my bash is out of date

**Comment by gildor2** [comment]
Your bash and perl are newer than ones I use to make a Windows build ...

**Comment by sorrowsin** [comment]
yeah, i will try to update and try again, thanks

**Comment by gildor2** [comment]
I've tried to remove UnCore.h on my side, and I've got this error:

    ERROR: cannot find file "UnCore.h" included from "Exporters/Export3D.cpp", directories used: [. ./Core ./Unreal ./libs/include ./libs ./libs/nvtt ./libs/zlib ./libs/libpng ./libs/PowerVR ./libs/detex ./libs/rijndael ./libs/includewin32 UmodelTool UI]

The difference from your side is: you have "../../something", while I have "./something". This should happen only if you'll run build.sh for some tool (Tools/PackageExtract etc), but shouldn't happen if you're running umodel's build.sh.

**Comment by sorrowsin** [comment]
hmmmm. I will re-download UEViewer

**Comment by sorrowsin** [comment]
i got farther than i did before, but this is now the error

`Unreal/Shaders/../Shaders.h does not exists, creating ...
Generating makefile from UmodelTool/umodel.project ...
Export3D.cpp
In file included from Exporters/Export3D.cpp:5:
./Unreal/UnrealMesh/UnMesh2.h:1684:3: error: expected ')'
                PROP_DROP(EnableCollisionforShadow)
                ^
./Unreal/TypeInfo.h:200:51: note: expanded from macro 'PROP_DROP'
#define PROP_DROP(Field, ...)                           CPropInfo(#Field __VA_OP...
                                                                         ^
./Unreal/UnrealMesh/UnMesh2.h:1684:3: note: to match this '('
./Unreal/TypeInfo.h:200:43: note: expanded from macro 'PROP_DROP'
#define PROP_DROP(Field, ...)                           CPropInfo(#Fiel...
                                                                 ^
In file included from Exporters/Export3D.cpp:5:
./Unreal/UnrealMesh/UnMesh2.h:1685:3: error: expected ')'
                PROP_DROP(bNoDynamicShadowCast)
                ^
./Unreal/TypeInfo.h:200:51: note: expanded from macro 'PROP_DROP'
#define PROP_DROP(Field, ...)                           CPropInfo(#Field __VA_OP...
                                                                         ^
./Unreal/UnrealMesh/UnMesh2.h:1685:3: note: to match this '('
./Unreal/TypeInfo.h:200:43: note: expanded from macro 'PROP_DROP'
#define PROP_DROP(Field, ...)                           CPropInfo(#Fiel...
                                                                 ^
In file included from Exporters/Export3D.cpp:5:
./Unreal/UnrealMesh/UnMesh2.h:1727:3: error: expected ')'
                PROP_DROP(bMakeTwoSideMesh)
                ^
./Unreal/TypeInfo.h:200:51: note: expanded from macro 'PROP_DROP'
#define PROP_DROP(Field, ...)                           CPropInfo(#Field __VA_OP...
                                                                         ^
./Unreal/UnrealMesh/UnMesh2.h:1727:3: note: to match this '('
./Unreal/TypeInfo.h:200:43: note: expanded from macro 'PROP_DROP'
#define PROP_DROP(Field, ...)                           CPropInfo(#Fiel...
                                                                 ^
In file included from Exporters/Export3D.cpp:5:
./Unreal/UnrealMesh/UnMesh2.h:1730:3: error: expected ')'
                PROP_DROP(HavokCollisionTypeStatic)
                ^
./Unreal/TypeInfo.h:200:51: note: expanded from macro 'PROP_DROP'
#define PROP_DROP(Field, ...)                           CPropInfo(#Field __VA_OP...
                                                                         ^
./Unreal/UnrealMesh/UnMesh2.h:1730:3: note: to match this '('
./Unreal/TypeInfo.h:200:43: note: expanded from macro 'PROP_DROP'
#define PROP_DROP(Field, ...)                           CPropInfo(#Fiel...
                                                                 ^
In file included from Exporters/Export3D.cpp:5:
./Unreal/UnrealMesh/UnMesh2.h:1731:3: error: expected ')'
                PROP_DROP(HavokCollisionTypeDynamic)
                ^
./Unreal/TypeInfo.h:200:51: note: expanded from macro 'PROP_DROP'
#define PROP_DROP(Field, ...)                           CPropInfo(#Field __VA_OP...
                                                                         ^
./Unreal/UnrealMesh/UnMesh2.h:1731:3: note: to match this '('
./Unreal/TypeInfo.h:200:43: note: expanded from macro 'PROP_DROP'
#define PROP_DROP(Field, ...)                           CPropInfo(#Fiel...
                                                                 ^
In file included from Exporters/Export3D.cpp:5:
./Unreal/UnrealMesh/UnMesh2.h:1732:3: error: expected ')'
                PROP_DROP(UseSimpleVisionCollision)
                ^
./Unreal/TypeInfo.h:200:51: note: expanded from macro 'PROP_DROP'
#define PROP_DROP(Field, ...)                           CPropInfo(#Field __VA_OP...
                                                                         ^
./Unreal/UnrealMesh/UnMesh2.h:1732:3: note: to match this '('
./Unreal/TypeInfo.h:200:43: note: expanded from macro 'PROP_DROP'
#define PROP_DROP(Field, ...)                           CPropInfo(#Fiel...
                                                                 ^
In file included from Exporters/Export3D.cpp:5:
./Unreal/UnrealMesh/UnMesh2.h:1733:3: error: expected ')'
                PROP_DROP(UseSimpleFootIKCollision)
                ^
./Unreal/TypeInfo.h:200:51: note: expanded from macro 'PROP_DROP'
#define PROP_DROP(Field, ...)                           CPropInfo(#Field __VA_OP...
                                                                         ^
./Unreal/UnrealMesh/UnMesh2.h:1733:3: note: to match this '('
./Unreal/TypeInfo.h:200:43: note: expanded from macro 'PROP_DROP'
#define PROP_DROP(Field, ...)                           CPropInfo(#Fiel...
                                                                 ^
In file included from Exporters/Export3D.cpp:5:
./Unreal/UnrealMesh/UnMesh2.h:1734:3: error: expected ')'
                PROP_DROP(NeverCollide)
                ^
./Unreal/TypeInfo.h:200:51: note: expanded from macro 'PROP_DROP'
#define PROP_DROP(Field, ...)                           CPropInfo(#Field __VA_OP...
                                                                         ^
./Unreal/UnrealMesh/UnMesh2.h:1734:3: note: to match this '('
./Unreal/TypeInfo.h:200:43: note: expanded from macro 'PROP_DROP'
#define PROP_DROP(Field, ...)                           CPropInfo(#Fiel...
                                                                 ^
In file included from Exporters/Export3D.cpp:5:
./Unreal/UnrealMesh/UnMesh2.h:1735:3: error: expected ')'
                PROP_DROP(SortShape)
                ^
./Unreal/TypeInfo.h:200:51: note: expanded from macro 'PROP_DROP'
#define PROP_DROP(Field, ...)                           CPropInfo(#Field __VA_OP...
                                                                         ^
./Unreal/UnrealMesh/UnMesh2.h:1735:3: note: to match this '('
./Unreal/TypeInfo.h:200:43: note: expanded from macro 'PROP_DROP'
#define PROP_DROP(Field, ...)                           CPropInfo(#Fiel...
                                                                 ^
In file included from Exporters/Export3D.cpp:5:
./Unreal/UnrealMesh/UnMesh2.h:1736:3: error: expected ')'
                PROP_DROP(LightMapCoordinateIndex)
                ^
./Unreal/TypeInfo.h:200:51: note: expanded from macro 'PROP_DROP'
#define PROP_DROP(Field, ...)                           CPropInfo(#Field __VA_OP...
                                                                         ^
./Unreal/UnrealMesh/UnMesh2.h:1736:3: note: to match this '('
./Unreal/TypeInfo.h:200:43: note: expanded from macro 'PROP_DROP'
#define PROP_DROP(Field, ...)                           CPropInfo(#Fiel...
                                                                 ^
In file included from Exporters/Export3D.cpp:5:
./Unreal/UnrealMesh/UnMesh2.h:1737:3: error: expected ')'
                PROP_DROP(LightMapScale)
                ^
./Unreal/TypeInfo.h:200:51: note: expanded from macro 'PROP_DROP'
#define PROP_DROP(Field, ...)                           CPropInfo(#Field __VA_OP...
                                                                         ^
./Unreal/UnrealMesh/UnMesh2.h:1737:3: note: to match this '('
./Unreal/TypeInfo.h:200:43: note: expanded from macro 'PROP_DROP'
#define PROP_DROP(Field, ...)                           CPropInfo(#Fiel...
                                                                 ^
11 errors generated.
make: *** [obj/umodel-osx/Export3D.o] Error 1`

I updated pearl with hombrew, but i dont know if my system is using the new one. that might not have anything to do with it but it seems updating bash seemed to move me past the first error, as i had downloaded and redownloaded UEViewer previously with the same error

**Comment by sorrowsin** [comment]
do i get this becuase of my compiler?

**Comment by gildor2** [comment]
This is a clang issue. The lines which has errors are using modern C++ standard.

**Comment by sorrowsin** [comment]
ok, thats what i thought. Well thanks for helping, hope you have a good day/night

**Comment by bmourit** [comment]
Changing the line:
        _CPP_STD = c++14_ 
to
        _CPP_STD = c++2a_
in the _common.project_ file  found in the root directory of the project, will allow successful compilation on macOS.

**Comment by gildor2** [comment]
What problem do you have with C++14?

**Comment by bmourit** [comment]
The same error messages as posted above about expected ")".
