### ISSUE TITLE
Evangelion Battlefield Crashing On Rigged Models

### ISSUE THREAD

**Issue by keesoudwater34** [gildor2/UEViewer#184]
honestly i can type about it a lot but a lot of the info is already in this page about it. https://www.gildor.org/smf/index.php?topic=7112.0 also with the pak it has it there. the only thing that does work is the non rigged meshes in ue 4.24

**Comment by gildor2** [comment]
First of all, this - https://github.com/gildor2/UEViewer/issues/113
There's a PR with the game's support, but I didn't have time to get into it yet - https://github.com/gildor2/UEViewer/pull/176

**Comment by keesoudwater34** [comment]
ah fair enough. i didnt see the thing about 113 so im sorry i didnt see that before. i did try to do a search to see if it was posted or not. so i apologise for not seeing finding that one earlier. hope i didnt cause you any annoyance. ill just keep track of 176 and take your time gildor. so i should be able to close this one without it affecting 176 right?
