### ISSUE TITLE
Latest Valorant version breaks Umodel

### ISSUE THREAD

**Issue by RumbleMike** [gildor2/UEViewer#189]
With the latest valorant patch being 2.02 pak files were change around and now UModel no longer supports VALORANT.

**Comment by gildor2** [comment]
UModel didn't have any special code for this game before, it did work just because it uses "standard" file formats/structures. Either you're using wrong options now, or the game received changes which are not compatible with vanilla engine. This is not an "issue" for me.

**Comment by FabianFG** [comment]
FYI the change is 8 new bytes before the guid in FPackageFileSummary.
Don't really know what they are used for but looks like it contains some size

**Comment by gildor2** [comment]
Forum says that everything works fine with the recent version of the game
https://www.gildor.org/smf/index.php/topic,7040.msg39118.html#msg39118

Who's wrong?

**Comment by FabianFG** [comment]
The format changed for sure but they have different update regions so I think the patch is not deployed everywhere yet

**Comment by gildor2** [comment]
In this case, supporting one region might break other ones?

**Comment by FabianFG** [comment]
Not really, every region will get that update, but they first deployed in US. Others will follow probably very soon

**Comment by RumbleMike** [comment]
The update has now been released for all regions.

**Comment by zeuxis69** [comment]
Yup, and this is the error for me - 

appMalloc: size=-2030151796 (total=29 Mbytes) <- FArray::Empty: 1262476449 x 12 <- FPackageFileSummary::Serialize4 <- FPackageFileSummary<<: Ver=0/0 <- UnPackage::UnPackage: /Game/Equippables/Guns/Rifles/AK/Cyberpunk2/1P/Models/GN_AK_Cyberpunk2_Lv3_Skelmesh.uasset, ver=518/0, game=ue4.24 <- UnPackage::LoadPackage(info): /Game/Equippables/Guns/Rifles/AK/Cyberpunk2/1P/Models/GN_AK_Cyberpunk2_Lv3_Skelmesh.uasset <- CUmodelApp::ShowPackageUI <- Main: umodel_build=1487

**Comment by Blenux** [comment]
Been fixed on the forums.

https://www.gildor.org/smf/index.php?PHPSESSID=ad747571fea750ed9237e25409d69903&topic=7040.60

**Comment by fill30** [comment]
I am getting this error below, is there a fix?
I dont need to buy more ram do I? 😆 

Memory: bad allocation size 1896941296 bytes
Call stack:
appMalloc: size=1896941296 (total=30 Mbytes) <- FArray::Empty: 873906324 x 12 <- FPackageFileSummary::Serialize4 <- FPackageFileSummary<<: Ver=0/0 <- UnPackage::UnPackage: /Game/Actor_SimpleWarmupTransition.uasset, ver=517/0, game=ue4.23 <- UnPackage::LoadPackage(info): /Game/Actor_SimpleWarmupTransition.uasset <- UIMenuItem::HandleCommand <- UIMenu::Popup <- UIBaseDialog::WndProc <- UIBaseDialog::CustomMessageLoop <- UIBaseDialog::ShowDialog: modal=1, title="Choose a package to open" <- CUmodelApp::ShowPackageUI <- Main: umodel_build=1487

**Comment by gildor2** [comment]
Did you ever read an issue?? I think NOT.

**Comment by Devostated** [comment]
> Did you ever read an issue?? I think NOT.

One guy said it works, maybe he didn't even update? I haven't met anyone who didn't have problems with the official release.
The fixed version of spiritovod works for everyone who had struggle with the latest valorant update.

> Been fixed on the forums by spiritovod
> 
> https://www.gildor.org/smf/index.php/topic,7040.msg39129.html#msg39129

**Comment by gildor2** [comment]
Ok. But anyway
1. this was a game which didn't have any special support in UModel, it worked just because worked
2. there was a report on the forum, so making an issue for that wasn't correct (I understand it wasn't you who created an issue)
