### ISSUE TITLE
Lineage 2 .ukx not working : " wrong export index 41 " 

### ISSUE THREAD

**Issue by l2ml2m** [gildor2/UEViewer#191]
Umodel cannot open animations from Lineage 2 anymore.

File tested: https://gofile.io/d/12yrFb can u help?
FUll game client: https://www.mediafire.com/file/ff4zm3oez3vnb7f/Korean_l2_full_2020_dec_29_.rar/file

Error message received in this file:

`
******** Loading object SkeletalMesh'LineageWeapons4.IceInvoke_avenger_m00_wp' ********

ERROR: Package "animations/LineageWeapons4.ukx": wrong export index 41
UnPackage::CreateExport: animations/LineageWeapons4.ukx:41 <- UnPackage::SerializeUObject <- USkeletalMesh::Serialize <- LoadObject: SkeletalMesh'LineageWeapons4.IceInvoke_avenger_m00_wp', pos=2DC3, ver=133/40, game=l2 <- UObject::EndLoad <- LoadWholePackage: animations/LineageWeapons4.ukx <- CUmodelApp::ShowPackageUI <- Main: umodel_build=1487

`

Other error messages from other file LineageWeapons3.ukx

`******** Loading object SkeletalMesh'LineageWeapons3.vampire_archer_weapone' ********

ERROR: Memory: bad allocation size -264241148 bytes
appMalloc: size=-264241148 (total=0 Mbytes) <- FArray::Empty: -66060287 x 4 <- TArray::SerializeSimple <- USkeletalMesh::Serialize <- LoadObject: SkeletalMesh'LineageWeapons3.vampire_archer_weapone', pos=6D223, ver=133/40, game=l2 <- UObject::EndLoad <- LoadWholePackage: LineageWeapons3.ukx <- CUmodelApp::ShowPackageUI <- Main: umodel_build=1487
`

**Comment by gildor2** [comment]
This is a known issue
https://www.gildor.org/smf/index.php/topic,6982.0.html
