### ISSUE TITLE
GObject

### ISSUE THREAD

**Issue by dschaf** [gildor2/UEViewer#192]
could this be used to pull fortnite gobject in the feature along with other cigs?

**Comment by gildor2** [comment]
Could you be more specific? I can't understand your question at all.

**Comment by dschaf** [comment]
> Could you be more specific? I can't understand your question at all.

im trying to pull fortnites signatures using ksdumper and ida and i was wondering if i could dump ue64 engine along with fortnite sdks using this ?

**Comment by gildor2** [comment]
Of course not. This is not a hacking tool, it just reads models/textures from assets.

**Comment by dschaf** [comment]
wat

**Comment by dschaf** [comment]
sexy ass

**Comment by dschaf** [comment]
do u have compiled form

**Comment by dschaf** [comment]
imma hack me some fortnite

**Comment by dschaf** [comment]
i cant seem to find the compiled version ive been looking here at the food menu
