### ISSUE TITLE
"Memory: bad allocation size 1073741824" Error on opening mesh

### ISSUE THREAD

**Issue by electroarch** [gildor2/UEViewer#196]
Hello, I am having a issue with opening any kind of mesh in UEViewer. I try to open any model, get that error. I am simply trying to export a mesh, but even without opening the mesh and simply right clicking the file and exporting it I get the error. I'm trying to export from Fortnite on the latest version of UEViewer, yes I have the oo2core dll's. If you know what could be causing this please let me know as I am simply trying to export a model from it to port into another game I want to mod. Thanks in advance.

**Comment by gildor2** [comment]
Fortnite has a special build at my Patreon site. This was mentioned in Fortnite forum thread, and on my twitter, many times.
https://www.gildor.org/smf/index.php/topic,3317.msg39231.html#msg39231
https://twitter.com/UGildor
