### ISSUE TITLE
[FORTNITE] Export animation / Chapter 2 season 6

### ISSUE THREAD

**Issue by Sal101010** [gildor2/UEViewer#202]
Problem : 

when you try to export an animation, nothing as exported. But if you try export a UASSET he work... And again the animation as not detected,  not loader and not be played. he say skeleton misssing... but i was pre charged when i have open the mesh before and last the animation....

![Capture d’écran 2021-03-18 020003](https://user-images.githubusercontent.com/80845373/111557901-e3fbca80-878d-11eb-80b1-f5e5d7cbcaee.png)
![Capture d’écran 2021-03-18 015306](https://user-images.githubusercontent.com/80845373/111557821-b1ea6880-878d-11eb-93e2-4f02415fbb67.png)

**Comment by gildor2** [comment]
Banned.
