### ISSUE TITLE
Unreal Engine or Blender 3D

### ISSUE THREAD

**Issue by h4xsLwV0Id** [gildor2/UEViewer#204]
I get confused. I want create animations of 3-4 seconds and sweet characters for NFT. Which one should I use? What are the pros and cons? Could you help me this subject? Thank you from now.

**Comment by gildor2** [comment]
I can't suggest anything. You should ask somewhere else.

**Comment by h4xsLwV0Id** [comment]
> I can't advise anything. You should ask somewhere else.

I don't know where to write :(

**Comment by gildor2** [comment]
I don't know too. I'm not creating animations, and I never used Blender.

**Comment by h4xsLwV0Id** [comment]
> I don't know too. I'm not creating animations, and I never used Blender.

thanks anyway
