### ISSUE TITLE
bulk export of static meshes issue

### ISSUE THREAD

**Issue by dhk-room101** [gildor2/UEViewer#208]
latest app/commit: when using GUI to bulk export static meshes, I get random errors, usually texture related

e.g.
`<- appFree <- TryExecuteInThread: ExportTexture <- Materials <- ExportCommonMeshData <- ExportStaticMeshLod <- Lod: 0 <- ExportObject: StaticMesh4'2hand_axe' <- ExportObjects <- ExportPackages <- CUmodelApp::ShowPackageUI <- Main: umodel_build=1538 <- WriteTGA <- TryExecuteInThread: ExportTexture`

commit `b520a47` (Jun 24, 2020): when using GUI to bulk export static meshes, no errors, but significantly slower

for testing I used Portal Defect (4.25) but it fails with other projects as well. In both cases the process is as follows:
start the app in GUI.
Point to the PAK folder
select 4.25 for game detection
change to flat view
Tools/scan content
sort by size and static mesh
bulk select all the static meshes ( nothing else)
click the export button
wait
latest app/commit: eventually errors out randomly 
commit `b520a47` (Jun 24, 2020): completed successfully, just slower

**Comment by gildor2** [comment]
I can't reproduce any issue. This doesn't mean that there's no any, but this mean - I can't find and fix the problem.
Is there any crash message in a log? E.g. some "first crash", followed by 2nd one, with texture exporter code?
BTW what CPU you have? How many cores are there?

**Comment by dhk-room101** [comment]
Yes, -nomt fix my issue! :-)

Did not see your edit, so I went through a lot of manual trial and error, see below details. You can close this or put on the back burner...
Thanks!

===============================================================
last commit without my issue present
`37c91dc` commit on Jul 6, 2020

**cannot test my issue**
error introduced `FPakVFS::LoadPakIndexLegacy <- FPakVFS::ReadDirectory:PakVer=9.0 <- RegisterGameFile:d:\Games\PortalDefect\TimeSplit\Content\Paks\/pakchunk2008-WindowsNoEditor.pak <- ScanGameDirectory <- appSetRootDirectory:dir=d:\Games\PortalDefect\TimeSplit\Content\Paks\ <- Main:umodel_build=(unversioned)`
first commit with error `FPakVFS::LoadPakIndexLegacy`
`a1a880a` commit on Jul 6, 2020

last commit with error `FPakVFS::LoadPakIndexLegacy`
`b0e9499` commit on Jul 15, 2020

**can test my issue again**
error fixed `FPakVFS::LoadPakIndexLegacy`
`cbdc699` commit on Jul 15, 2020 *FArray::GrowArray: fixed error*

my issue present in `cbdc699` commit on Jul 15, 2020
`Exception in thread 12280:
*** ERROR: Out of memory: failed to allocate 67108864 bytes
appMalloc:size=67108864 (total=2308 Mbytes) <- CTextureData::Decompress:fmt=PF_DXT1(5)
Exporting Texture2D Material__5_Metallic to f:/Work/Github/UEViewer/UmodelExport/Game/TimeLoop/Weapons/Weapon_Meshes/2hander/DecoAxe/Material__5_Metallic.tga`

Without hard proof, because unfortunately I cannot test it due to the `FPakVFS` error, I would say that the most likely culprit for my particular case/issue is commit `da0aae3` on Jul 15, 2020 *Multithreaded texture export*

```
Processor	AMD Ryzen 9 3900X 12-Core Processor               3.80 GHz
Installed RAM	64.0 GB
System type	64-bit operating system, x64-based processor

Edition	Windows 10 Pro
Version	20H2
OS build	19042.928
Experience	Windows Feature Experience Pack 120.2212.551.0
```

**Comment by gildor2** [comment]
Can you make a 64-bit build and test with multithreading again? I think that might be export of N textures at the same time, with multiple threads, might cause "out of memory" error as it grabs the whole 3Gb 32-bit space?

I definitely should make error reporting for multiple threads stable, currently it mixes messages from multiple threads and produces garbage.

**Comment by dhk-room101** [comment]
yep, 64 bit build fixed the issue. user error! :D I should have thought about it myself, I'm tired or stupid or both :) anyways, closing

**Comment by gildor2** [comment]
It wasn't a stupid issue. I didn't realize that running export with multiple threads may cause out of memory issue, so I definitely must fix it in some way.

**Comment by dhk-room101** [comment]
absolutely, you are correct, this issue should be addressed for the public application. I was referring to me as a programmer (at least as a wannabe one), I should have thought about the 2 GB memory limitation of the 32bit app. I closed this because  I'm using the repository and I can choose 64bit when compiling in Visual Studio, so my specific issue is fixed, it was an amateur error :)

which reminds me to ask: is there any reason for the app not to be 64bit by default?

**Comment by gildor2** [comment]
Just a quick answer to your question:
https://twitter.com/UGildor/status/1321431262838607877
