### ISSUE TITLE
Cannot open certain ue4 pak's (bad allocation size)

### ISSUE THREAD

**Issue by BlueAmulet** [gildor2/UEViewer#209]
Game: Conan Exiles (Mod)
Version: umodel build 1544 (Apr 18, 2021)
UE4 Version: 4.15

File: https://steamcommunity.com/sharedfiles/filedetails/?id=1765361591

Description:
On attempting to open SandstormFix.pak, I receive the following error message:
```
Memory: bad allocation size 704643072 bytes
appMalloc: size=704643072 (total=0 Mbytes) <- FArray::Empty: 704643072 x 1 <- FString<< <- ReadInfo: Index=2/9 <- FPakVFS::LoadPakIndexLegacy <- FPakVFS::ReadDirectory: PakVer=4.0 <- RegisterGameFile: D:\Steam\steamapps\workshop\content\440900\1765361591/SandstormFix.pak <- ScanGameDirectory <- appSetRootDirectory: dir=D:\Steam\steamapps\workshop\content\440900\1765361591 <- Main: umodel_build=1544
```
I've tried to use default settings, override game detection, set platform, but I get the same error every time.
I've noticed that u4pak also runs into issues reading files from this pak, failing to decompress files and seeking past file boundaries.

**Comment by gildor2** [comment]
Conan has custom pak file format.

**Comment by BlueAmulet** [comment]
Would you mind explaining how so? The pak file has the index magic at the last 44 bytes, and the index data itself also seems pretty standard, and other tools like u4pak decodes the index without issue.

**Comment by gildor2** [comment]
I think there's an unpacker script somewhere in game's thread on the forum.

**Comment by BlueAmulet** [comment]
Thank you for the information.
