### ISSUE TITLE
Skeletal Mesh Export Error (UE 4.25)

### ISSUE THREAD

**Issue by auraangel69** [gildor2/UEViewer#210]
I tried to open or export skeletal mesh from the new MotoGP game (MotoGP 21) then I got this error..
Serializing behind stopper (2B15D+9140000 > 57E9B)
FPakFile::Serialize: file=/Game/assets/graphics/characters/riders/riderShared/helmets/helmet060/skeletal_meshes/helmet060.uexp <- TArray::SerializeSimple <- FStaticLODModel4::SerializeRenderItem <- TArray::Serialize: 4/6 <- USkeletalMesh4::Serialize <- LoadObject: SkeletalMesh4'helmet060.helmet060', pos=2BEA6, ver=518/0, game=ue4.25 <- UObject::EndLoad <- LoadWholePackage: /Game/assets/graphics/characters/riders/riderShared/helmets/helmet060/skeletal_meshes/helmet060.uasset <- ExportPackages <- CUmodelApp::ShowPackageUI <- Main: umodel_build=1544

**Comment by gildor2** [comment]
There's a thread about this game
https://www.gildor.org/smf/index.php/topic,7721.0.html
Please post any questions there.
