### ISSUE TITLE
Export Fortnite models always show LODModels.Num()==LODInfo.Num()

### ISSUE THREAD

**Issue by kanomarin** [gildor2/UEViewer#211]
assertion failed: LODModels.Num() == LODInfo.Num()

USkeletalMesh4::ConvertMesh <- USkeletalMesh4::Serialize <- LoadObject: SkeletalMesh4'Head_Empty_Export.Head_Empty_Export', pos=1265, ver=522/0, game=ue4.26 <- UObject::EndLoad <- LoadWholePackage: /Game/Characters/Player/Common/Head_Empty/Head_Empty_Export.uasset <- ExportPackages <- UIMenuItem::HandleCommand <- UIMenu::Popup <- UIBaseDialog::WndProc <- UIBaseDialog::CustomMessageLoop <- UIBaseDialog::ShowDialog: modal=1, title="Choose a package to open" <- CUmodelApp::ShowPackageUI <- Main: umodel_build=1545

**Comment by floxay** [comment]
> You've set UE4.26, should be 4.27.

https://www.gildor.org/smf/index.php/topic,3317.msg39712.html#msg39712
