### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by XXxR4GALXxx** [gildor2/UEViewer#212]
https://github.com/gildor2/UEViewer/blob/6e82b958d62cf1eaa4bd571129dce1da8760421c/Unreal/UnrealPackage/UnPackage2.cpp#L330

What does it mean?  is it to specify the type of the object? 

...and where can i find the unreal 2.5 sdk?

thx!

**Comment by gildor2** [comment]
It's "shift" operator, overloaded for FArchive class for data serialization. Hopefully you know C++?

**Comment by XXxR4GALXxx** [comment]
> No idea. Just flags for FName.

Do u have full .ukx structure? I am converting the ukx file to another version. (based on your project).

what I got so far about the structure:

```
4 bytes - tag version
4 bytes - version and license??
0x30 bytes - FPackageFileSummary
8 bytes * generation.length - FGenerationInfo
```

what comes next? do you have the whole structure?

thx again!

**Comment by gildor2** [comment]
I don't have any docs.
