### ISSUE TITLE
Smite error

### ISSUE THREAD

**Issue by SakuraUO** [gildor2/UEViewer#213]
Hiya, everyone! 

I'm trying to extract audio only from Smite's game files...

The first attempt - I got this error...

Internal Oodle decompressor failed, oo2core_5_win32.dll not found

appDecompressOodle <- appDecompress: CompSize=24903 UncompSize=131072 Flags=0x208 Bytes=A62C <- DecompressBlock: block=52BD+6147 <- FUE3ArchiveReader::PrepareBuffer <- FUE3ArchiveReader::Serialize <- FArchive::ByteOrderSerialize <- FString<< <- Name: 0 <- UnPackage::LoadNameTable3 <- UnPackage::UnPackage: BattleGame/CookedPCConsole/Startup.upk, ver=893/0, game=ue3 <- UnPackage::LoadPackage(info): BattleGame/CookedPCConsole/Startup.upk <- UnPackage::LoadPackage(name): startup_xxx <- UnPackage::CreateImport: BattleGame/CookedPCConsole/NEITH_ASSETS_SF.upk:257 <- UnPackage::SerializeUObject <- TArray::Serialize: 2/3 <- SerializeFMaterialResource <- LoadObject: Material3'NEITH_ASSETS_SF.mat_arrow', pos=1538D12, ver=893/0, game=ue3 <- UObject::EndLoad <- LoadWholePackage: BattleGame/CookedPCConsole/NEITH_ASSETS_SF.upk <- ExportPackages <- CUmodelApp::ShowPackageUI <- Main: umodel_build=1544

However, this error was easy to solve. I got the dll it mentioned and then tried again.

This the second attempt of trying to extract...

OodleLZ_Decompress returned -1

appDecompressOodle <- appDecompress: CompSize=24903 UncompSize=131072 Flags=0x208 Bytes=A62C <- DecompressBlock: block=52BD+6147 <- FUE3ArchiveReader::PrepareBuffer <- FUE3ArchiveReader::Serialize <- FArchive::ByteOrderSerialize <- FString<< <- Name: 0 <- UnPackage::LoadNameTable3 <- UnPackage::UnPackage: BattleGame/CookedPCConsole/Startup.upk, ver=893/0, game=ue3 <- UnPackage::LoadPackage(info): BattleGame/CookedPCConsole/Startup.upk <- UnPackage::LoadPackage(name): startup_xxx <- UnPackage::CreateImport: BattleGame/CookedPCConsole/NEITH_ASSETS_SF.upk:257 <- UnPackage::SerializeUObject <- TArray::Serialize: 2/3 <- SerializeFMaterialResource <- LoadObject: Material3'NEITH_ASSETS_SF.mat_arrow', pos=1538D12, ver=893/0, game=ue3 <- UObject::EndLoad <- LoadWholePackage: BattleGame/CookedPCConsole/NEITH_ASSETS_SF.upk <- ExportPackages <- CUmodelApp::ShowPackageUI <- Main: umodel_build=1544

Looks to be the same error just didn't want to decompress... I'm wondering if I need manually put in the engine ver., so it doesn't give this error - or what?

**Comment by gildor2** [comment]
Smite has special game override.
