### ISSUE TITLE
Reimport custom textures to UE3

### ISSUE THREAD

**Issue by Bxaa** [gildor2/UEViewer#217]
Is it possible? 
Unpack ---> modify ---> Reimport
(UE3 engine, not 4)

Вообще существуют ли подобные рабочие инструменты?

**Comment by gildor2** [comment]
Есть что-то для Mass Effect, вроде для других игр тоже. Я wiki на github я когда-то добавлял какие-то ссылки, мне самому модификация игр не интересна, и UModel ничего для этого не делает.

**Comment by Bxaa** [comment]
Да большинство из них просто запихивают данные по смещению (предварительно сохраняя оригинальный заголовок текстур и .п) Всё это не является true импортом и само собой не будет работать, если менять текстуры например с 1024 на 4k (Я такое на коленке написать могу)
Что ваша программа не делает этого я знаю. Просто спросил, как у человека, который занимается этим
Спасибо за ответ.
