### ISSUE TITLE
Error while extracting pak files from Valorant after Patch 2.11

### ISSUE THREAD

**Issue by Code-MatrixDroid** [gildor2/UEViewer#218]
So... I've tried using every UE4 version from 4.22 to 4.27. All I get is this error.

Memory: bad allocation size -2037681352 bytes
appMalloc: size=-2037681352 (total=34 Mbytes) <- FArray::Empty: -885634662 x 12 <- FPackageFileSummary::Serialize4 <- FPackageFileSummary<<: Ver=0/0 <- UnPackage::UnPackage: /Engine/Animation/AresAnimBoneCompressionSettings.uasset, ver=517/0, game=ue4.22 <- UnPackage::LoadPackage(info): /Engine/Animation/AresAnimBoneCompressionSettings.uasset <- ScanContent <- UIMenuItem::HandleCommand <- UIMenu::Popup <- UIBaseDialog::WndProc <- UIBaseDialog::CustomMessageLoop <- UIBaseDialog::ShowDialog: modal=1, title="Choose a package to open" <- CUmodelApp::ShowPackageUI <- Main: umodel_build=1556

I'm new to this stuff tho.

**Comment by floxay** [comment]
VALORANT is currently on 4.25 and UModel needs some small modification since 2.02 to work (https://github.com/gildor2/UEViewer/pull/206)

You can either build the linked fork yourself or use spiritovod's build: https://www.gildor.org/smf/index.php/topic,7040.msg39129.html#msg39129
