### ISSUE TITLE
Build source code fail!

### ISSUE THREAD

**Issue by zgy001** [gildor2/UEViewer#222]
Hi,i'm new to the project and try to build it from source code.
i follow the steps :1.add buildtools/bin to path 2.exec cmd:bash build.sh --64
but i got error like:
F:\projects\UEViewer\Core\Core.h(8): fatal error C1083:  cannot open include file: “stdio.h”: No such file or directory 

i dont know how to fix .
here is my total log:
-------------------------------------------------------
Visual Studio Community 2019 toolset 142 (14.28.29910) [32 bit] found at "E:\vs2019\ide" ...                            Generating makefile from UmodelTool/umodel.project ...                                                                  ./libs/oodle/lib/Win32/oo2core_win32.lib doesn't exist                                                                  jom ./obj/umodel-vc-win32.mak                                                                                           Export3D.cpp                                                                                                            F:\projects\UEViewer\Core\Core.h(8): fatal error C1083: 无法打开包括文件: “stdio.h”: No such file or directory        Exporters.cpp                                                                                                           F:\projects\UEViewer\Core\Core.h(8): fatal error C1083: 无法打开包括文件: “stdio.h”: No such file or directory        ExportGLTF.cpp                                                                                                          F:\projects\UEViewer\Core\Core.h(8): fatal error C1083: 无法打开包括文件: “stdio.h”: No such file or directory        ExportTexture.cpp                                                                                                       F:\projects\UEViewer\libs\nvtt\nvcore/Debug.h(13): fatal error C1083: 无法打开包括文件: “stdio.h”: No such file or directory                                                                                                                  ExportPsk.cpp                                                                                                           F:\projects\UEViewer\Core\Core.h(8): fatal error C1083: 无法打开包括文件: “stdio.h”: No such file or directory        jom: F:\projects\UEViewer\./obj/umodel-vc-win32.mak [.\obj\umodel-win32\Export3D.obj] Error 2                           ExportMaterial.cpp                                                                                                      F:\projects\UEViewer\Core\Core.h(8): fatal error C1083: 无法打开包括文件: “stdio.h”: No such file or directory        ExportMd5.cpp                                                                                                           F:\projects\UEViewer\Core\Core.h(8): fatal error C1083: 无法打开包括文件: “stdio.h”: No such file or directory        ExportSound.cpp                                                                                                         F:\projects\UEViewer\Core\Core.h(8): fatal error C1083: 无法打开包括文件: “stdio.h”: No such file or directory        jom: F:\projects\UEViewer\./obj/umodel-vc-win32.mak [.\obj\umodel-win32\ExportMd5.obj] Error 2
jom: F:\projects\UEViewer\./obj/umodel-vc-win32.mak [.\obj\umodel-win32\ExportSound.obj] Error 2
jom: F:\projects\UEViewer\./obj/umodel-vc-win32.mak [.\obj\umodel-win32\ExportMaterial.obj] Error 2
jom: F:\projects\UEViewer\./obj/umodel-vc-win32.mak [.\obj\umodel-win32\Exporters.obj] Error 2
jom: F:\projects\UEViewer\./obj/umodel-vc-win32.mak [.\obj\umodel-win32\ExportGLTF.obj] Error 2
jom: F:\projects\UEViewer\./obj/umodel-vc-win32.mak [.\obj\umodel-win32\ExportPsk.obj] Error 2
jom: F:\projects\UEViewer\./obj/umodel-vc-win32.mak [.\obj\umodel-win32\ExportTexture.obj] Error 2
Build time: 0.9 sec
--------------------------------------------------------------------

**Comment by gildor2** [comment]
Probably you don't have UCRT SDK installed. Try compiling a simple C/C++ in Visual Studio, with stdio.h use, and see if it will work.

**Comment by zgy001** [comment]
simple C file can work.i want to know where UCRT SDK should be and how Umodel find it when compiling?it seems Umodel didnot find it.

**Comment by gildor2** [comment]
vc32tools locates it inside "Program Files/Windows Kits/10"

**Comment by zgy001** [comment]
i have the folder,but still fail

**Comment by 6ziv** [comment]
@zgy001  I suspect that you have something wrong with your Windows SDK installation.
I can only reproduce your output by manually removing (or renaming) the stdio header file, so I am not that sure.
Maybe you can start the "x64 Native Tools Command Prompt for VS 2019" and run "echo %INCLUDE%" to see if the correct path is in the list.
By the way, if you cannot find a better solution, uninstalling all installed versions of visual studio, cleaning up manually modified environment variables (if you did modify them), and reinstalling the latest VS as well as WIndows 10 SDK may help.
reference:
[1] [fatal error C1034: stdio.h: no include path set](https://social.msdn.microsoft.com/Forums/en-US/bfcffb6d-7abc-422a-8ab9-509f2403b106/fatal-error-c1034-stdioh-no-include-path-set)

**Comment by zgy001** [comment]
yeh,i guess someting went wrong with my vs config!
i installed vs into F colunm and windows kit too!Maybe my vs can find it corecttly but Umodel should find it in ../program files/..
after i delete the windows kit in F and copy it into C:/program files,my vs has the same error.
i donnot know how Umodel react with vs,so i decide to reinstall vs and windows kit  correctly  :)

**Comment by zgy001** [comment]
After reinstall ,finnally,i did it.Thanks for your all help!
