### ISSUE TITLE
[Feature request] UE4 Landscape heightmap/weightmap(s) export

### ISSUE THREAD

**Issue by dhk-room101** [gildor2/UEViewer#223]
This is a follow-up to our discussion we had a while back. I have my own sloppy way to stitch together heightmap/weightmap(s) from umap that have landscapes. But I'm thinking maybe it's more productive to consider integrating a better/easier way to do the same into ueviewer.

Basically when searching for umap, if `Scan Content` button was used, the maps that have landscapes show a counter in the Texture column. Perhaps right clicking on the umap should bring up a context menu with the option to export heightmap/weightmap(s)

Let me know if you need more info or a refresher about this. Thanks!

Unrelated side note: UE5 has a world partitions commandlet that converts UE4 world compositions into UE5 world partitions. And the addition of running the UE5 editor in command line mode along with commandlets brings me a lot of joy for some reason :D

**Comment by gildor2** [comment]
I doubt I'll ever have enough time for adding anything complex to UModel.

**Comment by dhk-room101** [comment]
No problem, I can give it a try myself.

In my forked repository I added UnMap.h and UnLandscape.h. When you have sometime maybe you can browse the landscape file I added just to confirm it follows your desired coding patterns. The landscape file also contains some basic foliage objects, I can re-factor that later if need

[https://github.com/dhk-room101/UEViewer/blob/master/Unreal/UnLandscape.h](https://github.com/dhk-room101/UEViewer/blob/master/Unreal/UnLandscape.h) 

Currently my approach is to dump all the landscape data into a text file and parse the text file separately and then stitch the textures according to the data parsed, but now I'll try to see if I'm smart enough to actually stay inside ueviewer scope. 
50-50 chance of success :D

Also I remember spiritovod poking around ueviewer, but I cannot contact him because I can't join the forum, maybe he is willing to participate, if you let him know? hopefully neither of you will play hard to get, because I still think it's a good feature to have :)

**Comment by gildor2** [comment]
Re: coding style. END_PROP_TABLE + followed Serialize are always incorrectly indented :)
PROP_ARRAY(SortedInstances, "int") - I'd replace "int" with PropType::Int, for easier refactoring if it will be required later.

Regarding forum - if you're getting "internal error" while registering, then check yourself with stopforumspam service - IP and email. Something is probably wrong. I'm using this service to block 99.9% of the spam.

**Comment by dhk-room101** [comment]
re: `PropType::Int` Good idea! I updated int and byte with PropType::Int and PropType::Byte

re: indented, I just added another `public:` right before Serialize, and it looks better, let me know if there is a better way

I will close this now, we would treat this feature as a community project :-)

**Comment by dhk-room101** [comment]
I'm getting a warning

`Struc property WeightmapScaleBias expected type PropType::FVector4 but read Vector4`


This is the code
```
	FVector4 WeightmapScaleBias;
	PROP_STRUC(WeightmapScaleBias, PropType::FVector4)
```

And I'm wondering what did I do wrong :D

**Comment by gildor2** [comment]
PROP_STRUC is not expecting PropType const. It expects the type name which will be stringified with PROP_STRUC macro. So, you should use

    PROP_STRUC(WeightmapScaleBias, Vector4)

**Comment by dhk-room101** [comment]
Oh, you're right, PropType is for PROP_ARRAY.

I made some small additions to UnObject.cpp, to simplify some of my code, if agreeable perhaps you are willing to merge in your code base. I did my best to follow your coding patterns. I sign all the changes with `//DHK`, because currently I do some sort of manual merging from my repository every time you release an update, and it's easier to keep track :-) 

more info here about my changes
[https://github.com/dhk-room101/UEViewer/blob/master/Unreal/UnObject.cpp](https://github.com/dhk-room101/UEViewer/blob/master/Unreal/UnObject.cpp)

**Comment by gildor2** [comment]
Your changes looks good.
I'd suppose using // DHK_BEGIN and // DHK_END, and probably adding a comment to your changes, for easier understanding later (just a practice from my work).
Take care of code formatting :) IDE's doesn't follow these macro blocks formatting automatically.

**Comment by dhk-room101** [comment]
Okay, sounds good, I did some quick updates for my comments
as for code formatting, it is one of the things Visual Studio confuses me the most. I tend to CTRL+K+D In Visual Studio a lot, but I usually try not to do it when tinkering in your classes, although muscle memory sometimes gets the best of me... :(

Another thing to discuss. As I'm owning this feature now with height map/weight map export, I did some changes
1. Added another extra option for the context menu
```cpp
+ NewMenuSeparator()
		+ NewMenuItem("Export Heightmap/Weightmap(s)")
		.SetCallback(BIND_LAMBDA([this]() { CloseDialog(TEXTURE); })) 
```
2. Added an EResult entry `TEXTURE`
3. Added a mode to handle `UIPackageDialog::TEXTURE`

I wanted to pick your brains about how best to handle texture stitching ( I don't remember the correct word for texture stitching , you mention it to me once before but I forgot )
Anyways more details here [https://github.com/dhk-room101/UEViewer/blob/master/UmodelTool/UmodelApp.cpp](https://github.com/dhk-room101/UEViewer/blob/master/UmodelTool/UmodelApp.cpp)
If you search for `//DHK_BEGIN` It should take you to a snippet where I identify the landscape components and do some quick calculations for future reference. All the data we need for the end result should be available now in memory

Now this is my current dilemma: I'm guessing, ideally, there is no reason to burden the current code base with yet another external library, unless really necessary. So in the current libraries available to ueviewer, is there one that can handle this texture stitching? I'm guessing PNG format should work just fine. I just need to figure out an easy (_for me, the less experienced programmer_ :D) way to stream the bytes from each individual piece into one big final array of bytes that I can then export to PNG.

Any suggestions or hints are appreciated! Once we accomplish this last step I'm currently working on, then the feature should be at least functional in beta :)

**Comment by gildor2** [comment]
No, I'm not aware of any stitching code. I use only PNG and DXT libraries, and these are intended only for texture encoding/decoding, with no geometric processing.

Stitching should be quite easy to do, just allocate a memory picture for the whole ("large") texture, then you'll need to re-map coordinates twice:
1. Texture tile coordinate to large texture coordinate - probably just LargeX = TileX * TileSize + CoordinateInsideTileX
2. Large texture coordinate to linear memory coordinate, e.g. Linear = LargeX + LargeY * LargeSizeX * PixelSize

Then process all tiles. Note that the LargeX/LargeY could became too large for being able to handle, e.g. 100k x 100k texture.

Sorry, probably I just didn't understand the question and explaining obvious things.

**Comment by dhk-room101** [comment]
No problem, I will try to figure out a way without any additional external library, but as a last resort would you be open to me using CImg or ImageMagick or something similar? assuming I can integrate them in the current UEViewer code base in my lab, like adding them to the `libs` folder and adding some entries to `common.project`. 

I'm asking because if I eventually implement this feature in my fork, if you eventually accept my changes into your repository, I want to stay inside your desired vision for acceptable external libraries :-)

**Comment by gildor2** [comment]
I'd prefer not integrating any third-party, especially for image processing things :)

**Comment by dhk-room101** [comment]
Yeah, I agree, I don't know why I'm so afraid of some simple math. Forget about third-party library for image processing, I already found and successfully used your already implemented function `WriteTGA`. It's just raw data, and all of a sudden I act like I'm all terrified hehehe. Still a few kinks to sort out, but the feature is pretty much in its last stretch to be completed, with minimal code addition and no external library needed.
