### ISSUE TITLE
Destroy All Humans 2020 Remake Mesh error - expected 8, serialized 12

### ISSUE THREAD

**Issue by Zaycool97** [gildor2/UEViewer#224]
Hello, Gildor2. 
First off, I'd like to give out an appreciation for your updating software of Umodel for game files made from Unreal Engine software for viewing purposes and not totally different stuff that could cause trouble for both you and other people.

Now for DAH!, there's this Krampus skin I'd like to view but somehow, the mesh gave me an error like this:

SerializeBulkArray <- FPositionVertexBuffer4<< <- FStaticLODModel4::SerializeRenderItem_Legacy <- FStaticLODModel4::SerializeRenderItem <- TArray::Serialize: 0/1 <- USkeletalMesh4::Serialize <- LoadObject: SkeletalMesh4'crypto.crypto', pos=16217D, ver=517/0 (unversioned), game=ue4.22 <- UObject::EndLoad <- LoadWholePackage: /DH/Content/Meshes/Characters/crypto.uasset <- CUmodelApp::ShowPackageUI <- UIMenuItem::HandleCommand <- UIMenuItem::HandleCommand <- CUmodelApp::WndProc <- VisualizerLoop <- Main: umodel_build=1550

Do you think you have any time to fix this issues for some mesh like this? Only for Crypto skins like the Krampus.

P.S. Sorry for you gaining a lot of messages from impatient people about this game according to one of your forums. Very uncool of them.

**Comment by gildor2** [comment]
Hi,
The forum thread has a special build provided by @spiritovod which has fixed compatibility with Destroy All Humans remake.
https://www.gildor.org/smf/index.php/topic,7129.30.html

**Comment by Zaycool97** [comment]
Hmm... I didn't know there's a special build for this specific game. Already used it and it works like a charm! Thanks!
