### ISSUE TITLE
Godfall - Errors: Serializing behind stopper, Memory: bad allocation size 

### ISSUE THREAD

**Issue by Jcbq01** [gildor2/UEViewer#225]
As posted above, on the current build of UModel i can open several of these models and assets but not all the direct error messages i get on two files are as follows:

Serializing behind stopper (2AA0B+4 > 2AA0D)
FPakFile::Serialize: file=/Game/Aperion/Environment/Cloud_Canyon/art/Architectures/decooration_pavement.uexp <- TArray::Serialize: 4427/7995512 <- FStaticMeshLODModel4<< <- TArray::Serialize: 2/6 <- UStaticMesh4::Serialize <- LoadObject: StaticMesh4'decooration_pavement.decooration_pavement', pos=2B691, ver=518/0 (unversioned), game=ue4.25 <- UObject::EndLoad <- LoadWholePackage: /Game/Aperion/Environment/Cloud_Canyon/art/Architectures/decooration_pavement.uasset <- CUmodelApp::ShowPackageUI <- CUmodelApp::ProcessKey: key=6F, down=1 <- VisualizerLoop <- Main: umodel_build=1550

Memory: bad allocation size -1744136208 bytes
appMalloc: size=-1744136208 (total=24 Mbytes) <- FArray::Empty: 464198570 x 24 <- TArray::Serialize: 0/0 <- FStaticMeshLODModel4<< <- TArray::Serialize: 2/6 <- UStaticMesh4::Serialize <- LoadObject: StaticMesh4'S_AirRealm_BulwarkStatue_01.S_AirRealm_BulwarkStatue_01', pos=144152, ver=518/0 (unversioned), game=ue4.25 <- UObject::EndLoad <- LoadWholePackage: /Game/Aperion/Environment/AirBiome/Props/Meshes/S_AirRealm_BulwarkStatue_01.uasset <- CUmodelApp::ShowPackageUI <- CUmodelApp::ProcessKey: key=6F, down=1 <- VisualizerLoop <- Main: umodel_build=1550

The files themselves come as unversioned out of the box however the development plugins mark them as 4.25 I can view and properly operate several of the models in question on the current build but not all. And will attempt to load it in an older version to determine if it is a versioning bug Placing here for posterity as of now

**Comment by gildor2** [comment]
https://www.gildor.org/smf/index.php/topic,7488.0.html
