### ISSUE TITLE
bug report.

### ISSUE THREAD

**Issue by zgy001** [gildor2/UEViewer#228]
In the latest source code
File:UnMesh4.cpp
Line:853.
it writes :`if (Ar.Game < GAME_UE4(27) || !StripFlags.IsClassDataStripped(1))`
means all GAME under 27 should do the next line.
i think it should change form || to &&,
because in UE4 source code ,they use 
`if( !StripFlags.IsClassDataStripped(1)))`
which means whether the next line run should depend on whether strip is or not .But when use ||,umodel just ignore the condition.
After i change it ,my crash when opening skeletalmesh disappear.
Am i correct?
Thanks

**Comment by gildor2** [comment]
This strip flags seems was introduced in 4.27, so trying to use it with older UE4 versions will introduce an error.

**Comment by zgy001** [comment]
i use the release source code 4.26.2,and it writes 'if( !StripFlags.IsClassDataStripped(1)))'.

**Comment by gildor2** [comment]
Well, I've reviewed UE4 code and you were partially right. The flags was introduce in UE4.23, so I've fixed the logic in e879659

**Comment by zgy001** [comment]
thanks for your great work!

**Comment by zgy001** [comment]
but i still wonder what you mean strip flags ? are they class FStripDataFlags?i see the class in 4.13 source code

**Comment by gildor2** [comment]
Yes.

	FStripDataFlags StripFlags(Ar, ClassDataStripFlags);
	...
	if (!StripFlags.IsClassDataStripped(DuplicatedVertices))
	{
		Ar << S.DuplicatedVerticesBuffer;
	}

**Comment by zgy001** [comment]
but i have the 4.13 code ,i see the class FStripDataFlags exist.maybe unreal introduced it earlier than 4.23?

**Comment by gildor2** [comment]
FStripDataFlags class exists since 4.0. It just wasn't used for FSkelMeshRenderSection serialization.

**Comment by zgy001** [comment]
ok,i know it clearly now ,thanks for your explanation.

**Comment by gildor2** [comment]
Thank you for reviewing the code
