### ISSUE TITLE
LODModels.Num issue - Fortnite Chapter 17

### ISSUE THREAD

**Issue by DerEnderman** [gildor2/UEViewer#230]
assertion failed: LODModels.Num() == LODInfo.Num()

USkeletalMesh4::ConvertMesh <- USkeletalMesh4::Serialize <- LoadObject: SkeletalMesh4'M_MED_Agent_Ace.M_MED_Agent_Ace', pos=5344B, ver=522/0, game=ue4.26 <- UObject::EndLoad <- LoadWholePackage: /Game/Characters/Player/Male/Medium/Bodies/M_MED_Agent_Ace/Meshe/M_MED_Agent_Ace.uasset <- CUmodelApp::ShowPackageUI <- Main: umodel_build=1562

Can someone fix this?

**Comment by gildor2** [comment]
Another one...
#113
