### ISSUE TITLE
Trojan:Win32/Cloxer.D!cl in current download

### ISSUE THREAD

**Issue by chrisan** [gildor2/UEViewer#87]
As of this time, http://www.gildor.org/down/43/umodel/umodel_win32.zip, is giving me a trojan virus warning

![image](https://user-images.githubusercontent.com/3704774/43969280-981add42-9c97-11e8-96c3-a34084a99444.png)

**Comment by gildor2** [comment]
This is a known issue. I have no idea how to shut up Windows Defender. I see it just changed "virus" name.
http://www.gildor.org/smf/index.php/topic,6125.0.html

**Comment by effolkronium** [comment]
I haven't reproduced that with latest updated windows defender. Can you try ?

**Comment by gildor2** [comment]
Just in case, I've submitted recent umodel.exe to Microsoft's online scanner
https://www.microsoft.com/en-us/wdsi/filesubmission

Here are results:
https://www.microsoft.com/en-us/wdsi/submission/3cfdd669-7b41-4957-aa07-fec6c037c575

I have no idea if umodel.exe is still detected as malware by Defender (I use Windows 8.1 with disabled Defender), but just in case, I've provided these results.

**Comment by chrisan** [comment]
I no longer get the warning, thanks!
